from flask import Blueprint, url_for
from app import sanitizer
from app.helpers.general_helpers import CurrentObjectAction, CurrentObjectInfo, SidebarElement, SidebarElementSublink
from app.helpers.projects_helpers import EnvironmentObjectAttrs, register_environment
from app.extensions.moment import moment
import app.models as models
from flask_babel import lazy_gettext as _l
from flask_login import login_required
from flask_login import current_user
from app.helpers.roles import project_role_can_make_action


bp = Blueprint('pentest_events', __name__, url_prefix='/pentest-events')
import app.controllers.research_events.routes


@bp.before_request
@login_required
def check_login_required():
    pass


def sidebar(current_object, act: str, **kwargs):
    con = current_object.__class__.__name__
    if con == 'Project':
        proj = current_object
    elif "proj" in kwargs:
        proj = kwargs["proj"]
    else:
        proj = current_object.project
    sels = []
    if project_role_can_make_action(current_user, models.PentestResearchEvent(), 'index', project=proj):
        sel1 = SidebarElementSublink(models.PentestResearchEvent.Meta.verbose_name_plural, url_for('pentest_events.researcher_event_index', project_id=proj.id), con=='PentestResearchEvent' and act == 'index')
        sels.append(sel1)
    if project_role_can_make_action(current_user, models.PentestResearchEvent(), 'create', project=proj):
        sel2 = SidebarElementSublink(_l("Add new researcher event"), url_for('pentest_events.researcher_event_new', project_id=proj.id), con=='PentestResearchEvent' and act == 'new')
        sels.append(sel2)
    if project_role_can_make_action(current_user, models.PentestOrganizationDetectionEvent(), 'index', project=proj):
        sel3 = SidebarElementSublink(models.PentestOrganizationDetectionEvent.Meta.verbose_name_plural, url_for('pentest_events.organization_detection_event_index', project_id=proj.id), con=='PentestOrganizationDetectionEvent' and act == 'index')
        sels.append(sel3)
    if project_role_can_make_action(current_user, models.PentestOrganizationDetectionEvent(), 'create', project=proj):
        sel4 = SidebarElementSublink(_l("Add new detection event"), url_for('pentest_events.organization_detection_event_new', project_id=proj.id), con=='PentestOrganizationDetectionEvent' and act == 'new')
        sels.append(sel4)
    if project_role_can_make_action(current_user, models.PentestResearchEvent(), 'show_timeline', project=proj) or project_role_can_make_action(current_user, models.PentestOrganizationDetectionEvent(), 'show_timeline', project=proj):
        sel5 = SidebarElementSublink(_l("Events timeline"), url_for('pentest_events.all_events_timeline', project_id=proj.id), con=='PentestResearchEvent' and act == 'timeline')
        sels.append(sel5)
    if len(sels) == 0:
        return None
    return [SidebarElement(_l("Research events"), url_for('pentest_events.researcher_event_index', project_id=proj.id), models.PentestResearchEvent.Meta.icon, con in ["PentestResearchEvent", "PentestOrganizationDetectionEvent"], sels)]


def environment(obj, action, **kwargs):
    acts = []
    if isinstance(obj, models.PentestResearchEvent):
        match action:
            case 'index':
                title = _l("Research events")
                if project_role_can_make_action(current_user, obj, 'create'):
                    act1 = CurrentObjectAction(_l("Create new event"), "fa-solid fa-square-plus", url_for('pentest_events.researcher_event_new', project_id=obj.project.id))
                    acts.append(act1)
                current_object = CurrentObjectInfo(obj.Meta.verbose_name_plural, obj.Meta.icon, subtitle=_l("Events generated by researchers and which can be detected"), actions=acts)
            case 'new':
                title = _l("Add new research event")
                current_object = CurrentObjectInfo(title, "fa-solid fa-square-plus", subtitle=obj.project.fulltitle)
            case 'show':
                title = _l("Research event #%(event_id)s", event_id=obj.id)
                if project_role_can_make_action(current_user, obj, 'update'):
                    act1 = CurrentObjectAction(_l("Edit"), "fa-solid fa-square-pen", url_for('pentest_events.researcher_event_edit', event_id=obj.id))
                    acts.append(act1)
                if project_role_can_make_action(current_user, obj, 'delete'):
                    act2 = CurrentObjectAction(_l("Delete"), "fa-solid fa-trash", url_for('pentest_events.researcher_event_delete', event_id=obj.id), confirm=_l("Are you sure you want to delete these event?"), btn_class='btn-danger', method='DELETE')
                    acts.append(act2)
                current_object = CurrentObjectInfo(_l("Event %(event_title)s", event_title=obj.title), obj.Meta.icon, subtitle=sanitizer.markup(_l('Created by <a href="%(link)s">%(created_by)s</a> %(date)s', link=url_for('users.user_show', user_id=obj.created_by.id), created_by=sanitizer.pure_text(obj.created_by.title), date=str(moment(obj.created_at).fromNow()))), actions=acts)
            case 'edit':
                title = _l("Edit research event #%(event_id)s", event_id=obj.id)
                current_object = CurrentObjectInfo(title, "fa-solid fa-square-pen", subtitle=obj.project.fulltitle)
            case 'timeline':
                title = _l("Events timeline")
                current_object = CurrentObjectInfo(title, "fa-solid fa-timeline", subtitle=_l("Comparison between research events and exposure detection events"))
    elif isinstance(obj, models.PentestOrganizationDetectionEvent):
        match action:
            case 'index':
                title = _l("Organization detection events")
                if project_role_can_make_action(current_user, obj, 'create'):
                    act1 = CurrentObjectAction(_l("Create new event"), "fa-solid fa-square-plus", url_for('pentest_events.organization_detection_event_new', project_id=obj.project.id))
                    acts.append(act1)
                current_object = CurrentObjectInfo(obj.Meta.verbose_name_plural, obj.Meta.icon, subtitle=_l("Events created in the organization, indicating the impact of researchers on resources"), actions=acts)
            case 'new':
                title = _l("Add new organization detection event")
                current_object = CurrentObjectInfo(title, "fa-solid fa-square-plus", subtitle=obj.project.fulltitle)
            case 'show':
                title = _l("Organization detection event #%(event_id)s", event_id=obj.id)
                if project_role_can_make_action(current_user, obj, 'update'):
                    act1 = CurrentObjectAction(_l("Edit"), "fa-solid fa-square-pen", url_for('pentest_events.organization_detection_event_edit', event_id=obj.id))
                    acts.append(act1)
                if project_role_can_make_action(current_user, obj, 'delete'):
                    act2 = CurrentObjectAction(_l("Delete"), "fa-solid fa-trash", url_for('pentest_events.organization_detection_event_delete', event_id=obj.id), confirm=_l("Are you sure you want to delete these event?"), btn_class='btn-danger', method='DELETE')
                    acts.append(act2)
                current_object = CurrentObjectInfo(_l("Organization detection event %(event_id)s", event_id=obj.id), obj.Meta.icon, subtitle=sanitizer.markup(_l('Created by <a href="%(link)s">%(created_by)s</a> %(date)s', link=url_for('users.user_show', user_id=obj.created_by.id), created_by=sanitizer.pure_text(obj.created_by.title), date=str(moment(obj.created_at).fromNow()))), actions=acts)
            case 'edit':
                title = _l("Edit organization detection event event #%(event_id)s", event_id=obj.id)
                current_object = CurrentObjectInfo(title, "fa-solid fa-square-pen", subtitle=obj.project.fulltitle)
    else:
        return {}
    return {'title': title, 'current_object': current_object, 'archived': obj.project.archived}


register_environment(EnvironmentObjectAttrs('PentestResearchEvent', sidebar, environment), 'Issue')