name: Простой пример использования GitVerse CI/CD
on:
 push:
jobs:
  build-test:
    name: Test context
    # для примера мы используем запуск на облачном раннере https://gitverse.ru/docs/knowledge-base/actions/cloud-runners/
    runs-on: ubuntu-cloud-runner
    steps:
      - name: Checkout to the branch
        uses: https://github.com/actions/checkout@v3
      - name: Display Workflow
        run: echo ${{ gitverse.workflow }}
      - name: Display repository name
        run: echo ${{ gitverse.Repository }}
      - name: Display repository owner
        run: echo ${{ gitverse.repository_owner }}
      - name: Display actor
        run: echo ${{ gitverse.actor }}
