name: Демонстрация GitVerse Cloud CI/CD
on:
  push:
jobs:
  build-test:
    name: Cloud Runner Demo
    runs-on: ubuntu-cloud-runner
    container:
      options: --cpus=0.5 --memory=2G --net=bridge ## Ограничения по CPU (50%) и RAM
    steps:
      - name: Display event name
        run: echo ${{ gitverse.event_name }}
      - name: Display Workflow
        run: echo ${{ gitverse.workflow }}
      - name: Display repository name
        run: echo ${{ gitverse.Repository}}
      - name: Display repository owner
        run: echo ${{ gitverse.repository_owner }}
      - name: Display actor
        run: echo ${{ gitverse.actor }}
