"""Добавлены стили графа сети

Revision ID: 07f7d8ea487d
Revises: f47e0bd8f56a
Create Date: 2025-07-15 01:09:09.607227

"""
from alembic import op
import sqlalchemy as sa
import app


# revision identifiers, used by Alembic.
revision = '07f7d8ea487d'
down_revision = 'f47e0bd8f56a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('default_port_and_transport_proto', schema=None) as batch_op:
        batch_op.alter_column('transport_level_protocol_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('access_protocol_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('user_theme_style', schema=None) as batch_op:
        batch_op.add_column(sa.Column('network_on_graph_color', sa.String(length=40), server_default='green', nullable=False))
        batch_op.add_column(sa.Column('normal_host_color', sa.String(length=40), server_default='#0000ff', nullable=False))
        batch_op.add_column(sa.Column('service_on_graph_color', sa.String(length=40), server_default='yellow', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_theme_style', schema=None) as batch_op:
        batch_op.drop_column('service_on_graph_color')
        batch_op.drop_column('normal_host_color')
        batch_op.drop_column('network_on_graph_color')

    with op.batch_alter_table('default_port_and_transport_proto', schema=None) as batch_op:
        batch_op.alter_column('access_protocol_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('transport_level_protocol_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
