"""Мелкие правки моделей

Revision ID: 1115b88acd5c
Revises: 3debb2b6d246
Create Date: 2025-08-23 09:22:51.911657

"""
from alembic import op
import sqlalchemy as sa
import app


# revision identifiers, used by Alembic.
revision = '1115b88acd5c'
down_revision = '3debb2b6d246'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('access_protocol', schema=None) as batch_op:
        batch_op.alter_column('string_slug',
               existing_type=sa.VARCHAR(length=50),
               type_=app.models.datatypes.LimitedLengthString(length=80),
               existing_nullable=False)

    with op.batch_alter_table('application_language', schema=None) as batch_op:
        batch_op.alter_column('string_slug',
               existing_type=sa.VARCHAR(length=50),
               type_=app.models.datatypes.LimitedLengthString(length=80),
               existing_nullable=False)

    with op.batch_alter_table('check_wordlist', schema=None) as batch_op:
        batch_op.alter_column('string_slug',
               existing_type=sa.VARCHAR(length=50),
               type_=app.models.datatypes.LimitedLengthString(length=80),
               existing_nullable=False)

    with op.batch_alter_table('critical_vulnerability', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_critical_vulnerability_created_at'))

    with op.batch_alter_table('device_model', schema=None) as batch_op:
        batch_op.alter_column('string_slug',
               existing_type=sa.VARCHAR(length=50),
               type_=app.models.datatypes.LimitedLengthString(length=80),
               existing_nullable=False)

    with op.batch_alter_table('device_type', schema=None) as batch_op:
        batch_op.alter_column('string_slug',
               existing_type=sa.VARCHAR(length=50),
               type_=app.models.datatypes.LimitedLengthString(length=80),
               existing_nullable=False)
        batch_op.add_column(sa.Column('icon_class', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('icon_number', sa.Integer(), nullable=True))

    with op.batch_alter_table('device_vendor', schema=None) as batch_op:
        batch_op.alter_column('string_slug',
               existing_type=sa.VARCHAR(length=50),
               type_=app.models.datatypes.LimitedLengthString(length=80),
               existing_nullable=False)

    with op.batch_alter_table('evidence_of_event_detected', schema=None) as batch_op:
        batch_op.alter_column('string_slug',
               existing_type=sa.VARCHAR(length=50),
               type_=app.models.datatypes.LimitedLengthString(length=80),
               existing_nullable=False)

    with op.batch_alter_table('evidence_of_event_prevented', schema=None) as batch_op:
        batch_op.alter_column('string_slug',
               existing_type=sa.VARCHAR(length=50),
               type_=app.models.datatypes.LimitedLengthString(length=80),
               existing_nullable=False)

    with op.batch_alter_table('host_status', schema=None) as batch_op:
        batch_op.alter_column('string_slug',
               existing_type=sa.VARCHAR(length=50),
               type_=app.models.datatypes.LimitedLengthString(length=80),
               existing_nullable=False)

    with op.batch_alter_table('issue_status', schema=None) as batch_op:
        batch_op.alter_column('string_slug',
               existing_type=sa.VARCHAR(length=50),
               type_=app.models.datatypes.LimitedLengthString(length=80),
               existing_nullable=False)

    with op.batch_alter_table('issue_template', schema=None) as batch_op:
        batch_op.alter_column('string_slug',
               existing_type=sa.VARCHAR(length=50),
               type_=app.models.datatypes.LimitedLengthString(length=80),
               existing_nullable=False)

    with op.batch_alter_table('mac_address_info', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=120),
               existing_nullable=False)

    with op.batch_alter_table('mitre_attack_tactic', schema=None) as batch_op:
        batch_op.alter_column('string_slug',
               existing_type=sa.VARCHAR(length=50),
               type_=app.models.datatypes.LimitedLengthString(length=80),
               existing_nullable=False)

    with op.batch_alter_table('mitre_attack_technique', schema=None) as batch_op:
        batch_op.alter_column('string_slug',
               existing_type=sa.VARCHAR(length=50),
               type_=app.models.datatypes.LimitedLengthString(length=80),
               existing_nullable=False)

    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_note_created_at'))

    with op.batch_alter_table('note_importance', schema=None) as batch_op:
        batch_op.alter_column('string_slug',
               existing_type=sa.VARCHAR(length=20),
               type_=app.models.datatypes.LimitedLengthString(length=80),
               existing_nullable=False)

    with op.batch_alter_table('operation_system_family', schema=None) as batch_op:
        batch_op.alter_column('string_slug',
               existing_type=sa.VARCHAR(length=50),
               type_=app.models.datatypes.LimitedLengthString(length=80),
               existing_nullable=False)
        batch_op.add_column(sa.Column('icon_class', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('icon_number', sa.Integer(), nullable=True))
        batch_op.drop_column('icon')

    with op.batch_alter_table('programming_language', schema=None) as batch_op:
        batch_op.alter_column('string_slug',
               existing_type=sa.VARCHAR(length=50),
               type_=app.models.datatypes.LimitedLengthString(length=80),
               existing_nullable=False)

    with op.batch_alter_table('programming_language_class', schema=None) as batch_op:
        batch_op.alter_column('string_slug',
               existing_type=sa.VARCHAR(length=50),
               type_=app.models.datatypes.LimitedLengthString(length=80),
               existing_nullable=False)

    with op.batch_alter_table('programming_language_theme', schema=None) as batch_op:
        batch_op.alter_column('string_slug',
               existing_type=sa.VARCHAR(length=50),
               type_=app.models.datatypes.LimitedLengthString(length=80),
               existing_nullable=False)

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_created_at'))

    with op.batch_alter_table('project_additional_field', schema=None) as batch_op:
        batch_op.alter_column('string_slug',
               existing_type=sa.VARCHAR(length=50),
               type_=app.models.datatypes.LimitedLengthString(length=80),
               existing_nullable=False)

    with op.batch_alter_table('project_additional_field_group', schema=None) as batch_op:
        batch_op.alter_column('string_slug',
               existing_type=sa.VARCHAR(length=50),
               type_=app.models.datatypes.LimitedLengthString(length=80),
               existing_nullable=False)

    with op.batch_alter_table('project_role', schema=None) as batch_op:
        batch_op.alter_column('string_slug',
               existing_type=sa.VARCHAR(length=50),
               type_=app.models.datatypes.LimitedLengthString(length=80),
               existing_nullable=False)

    with op.batch_alter_table('project_task', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=60),
               existing_nullable=False)

    with op.batch_alter_table('project_task_priority', schema=None) as batch_op:
        batch_op.alter_column('string_slug',
               existing_type=sa.VARCHAR(length=50),
               type_=app.models.datatypes.LimitedLengthString(length=80),
               existing_nullable=False)

    with op.batch_alter_table('project_task_template', schema=None) as batch_op:
        batch_op.alter_column('string_slug',
               existing_type=sa.VARCHAR(length=50),
               type_=app.models.datatypes.LimitedLengthString(length=80),
               existing_nullable=False)
        batch_op.alter_column('task_title',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=60),
               existing_nullable=False)

    with op.batch_alter_table('project_task_tracker', schema=None) as batch_op:
        batch_op.alter_column('string_slug',
               existing_type=sa.VARCHAR(length=50),
               type_=app.models.datatypes.LimitedLengthString(length=80),
               existing_nullable=False)

    with op.batch_alter_table('proof_of_concept', schema=None) as batch_op:
        batch_op.alter_column('string_slug',
               existing_type=sa.VARCHAR(length=50),
               type_=app.models.datatypes.LimitedLengthString(length=80),
               existing_nullable=False)
        batch_op.drop_constraint(batch_op.f('uq_proof_of_concept_string_slug'), type_='unique')
        batch_op.create_index(batch_op.f('ix_proof_of_concept_string_slug'), ['string_slug'], unique=True)

    with op.batch_alter_table('service_port_state', schema=None) as batch_op:
        batch_op.alter_column('string_slug',
               existing_type=sa.VARCHAR(length=50),
               type_=app.models.datatypes.LimitedLengthString(length=80),
               existing_nullable=False)

    with op.batch_alter_table('service_transport_level_protocol', schema=None) as batch_op:
        batch_op.alter_column('string_slug',
               existing_type=sa.VARCHAR(length=50),
               type_=app.models.datatypes.LimitedLengthString(length=80),
               existing_nullable=False)

    with op.batch_alter_table('task_state', schema=None) as batch_op:
        batch_op.alter_column('string_slug',
               existing_type=sa.VARCHAR(length=50),
               type_=app.models.datatypes.LimitedLengthString(length=80),
               existing_nullable=False)

    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.alter_column('string_slug',
               existing_type=sa.VARCHAR(length=50),
               type_=app.models.datatypes.LimitedLengthString(length=80),
               existing_nullable=False)

    with op.batch_alter_table('user_theme_style', schema=None) as batch_op:
        batch_op.alter_column('string_slug',
               existing_type=sa.VARCHAR(length=50),
               type_=app.models.datatypes.LimitedLengthString(length=80),
               existing_nullable=False)

    with op.batch_alter_table('vulnerable_environment_type', schema=None) as batch_op:
        batch_op.alter_column('string_slug',
               existing_type=sa.VARCHAR(length=50),
               type_=app.models.datatypes.LimitedLengthString(length=80),
               existing_nullable=False)
    
    authentication_method_enum = sa.Enum('PASSWORD', 'REQUEST_HEADER', name='authenticationmethodenum')
    authentication_method_enum.create(op.get_bind())
    with op.batch_alter_table('global_settings', schema=None) as batch_op:
        batch_op.drop_column('authentication_method')
        batch_op.add_column(sa.Column('authentication_method', sa.Enum('PASSWORD', 'REQUEST_HEADER', name='authenticationmethodenum'),
                                      nullable=False, server_default=sa.text("'PASSWORD'")))
    
    project_additional_field_type_enum = sa.Enum("StringField", "TextAreaField", "IntegerField", "BooleanField",
                                                 "DateField", "WysiwygField", name='projectadditionalparameterfieldtype')
    project_additional_field_type_enum.create(op.get_bind(), checkfirst=True)

    with op.batch_alter_table('project_additional_field', schema=None) as batch_op:
        batch_op.drop_column('field_type')
        batch_op.add_column(sa.Column('field_type', sa.Enum("StringField", "TextAreaField", "IntegerField", "BooleanField",
                                                            "DateField", "WysiwygField", name="projectadditionalparameterfieldtype"),
                                      nullable=False, server_default=sa.text("'StringField'")))
    
    op.create_table('host_label',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('string_slug', app.models.datatypes.LimitedLengthString(length=80), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('icon_class', sa.String(length=30), nullable=True),
    sa.Column('icon_color', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_host_label'))
    )
    with op.batch_alter_table('host_label', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_host_label_string_slug'), ['string_slug'], unique=True)

    op.create_table('network_icon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('string_slug', app.models.datatypes.LimitedLengthString(length=80), nullable=False),
    sa.Column('title', sa.String(length=30), nullable=False),
    sa.Column('icon_number', sa.Integer(), nullable=True),
    sa.Column('icon_class', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_network_icon'))
    )
    with op.batch_alter_table('network_icon', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_network_icon_string_slug'), ['string_slug'], unique=True)

    op.create_table('host_by_label',
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.Column('label_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['host_id'], ['host.id'], name=op.f('fk_host_by_label_host_id_host'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['label_id'], ['host_label.id'], name=op.f('fk_host_by_label_label_id_host_label'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('host_id', 'label_id', name=op.f('pk_host_by_label'))
    )
    with op.batch_alter_table('network', schema=None) as batch_op:
        batch_op.add_column(sa.Column('icon_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_network_icon_id_network_icon'), 'network_icon', ['icon_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vulnerable_environment_type', schema=None) as batch_op:
        batch_op.alter_column('string_slug',
               existing_type=app.models.datatypes.LimitedLengthString(length=80),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('user_theme_style', schema=None) as batch_op:
        batch_op.alter_column('string_slug',
               existing_type=app.models.datatypes.LimitedLengthString(length=80),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.alter_column('string_slug',
               existing_type=app.models.datatypes.LimitedLengthString(length=80),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('task_state', schema=None) as batch_op:
        batch_op.alter_column('string_slug',
               existing_type=app.models.datatypes.LimitedLengthString(length=80),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('service_transport_level_protocol', schema=None) as batch_op:
        batch_op.alter_column('string_slug',
               existing_type=app.models.datatypes.LimitedLengthString(length=80),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('service_port_state', schema=None) as batch_op:
        batch_op.alter_column('string_slug',
               existing_type=app.models.datatypes.LimitedLengthString(length=80),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('proof_of_concept', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_proof_of_concept_string_slug'))
        batch_op.create_unique_constraint(batch_op.f('uq_proof_of_concept_string_slug'), ['string_slug'])
        batch_op.alter_column('string_slug',
               existing_type=app.models.datatypes.LimitedLengthString(length=80),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('project_task_tracker', schema=None) as batch_op:
        batch_op.alter_column('string_slug',
               existing_type=app.models.datatypes.LimitedLengthString(length=80),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('project_task_template', schema=None) as batch_op:
        batch_op.alter_column('task_title',
               existing_type=sa.String(length=60),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
        batch_op.alter_column('string_slug',
               existing_type=app.models.datatypes.LimitedLengthString(length=80),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('project_task_priority', schema=None) as batch_op:
        batch_op.alter_column('string_slug',
               existing_type=app.models.datatypes.LimitedLengthString(length=80),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('project_task', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.String(length=60),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)

    with op.batch_alter_table('project_role', schema=None) as batch_op:
        batch_op.alter_column('string_slug',
               existing_type=app.models.datatypes.LimitedLengthString(length=80),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('project_additional_field_group', schema=None) as batch_op:
        batch_op.alter_column('string_slug',
               existing_type=app.models.datatypes.LimitedLengthString(length=80),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('programming_language_theme', schema=None) as batch_op:
        batch_op.alter_column('string_slug',
               existing_type=app.models.datatypes.LimitedLengthString(length=80),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('programming_language_class', schema=None) as batch_op:
        batch_op.alter_column('string_slug',
               existing_type=app.models.datatypes.LimitedLengthString(length=80),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('programming_language', schema=None) as batch_op:
        batch_op.alter_column('string_slug',
               existing_type=app.models.datatypes.LimitedLengthString(length=80),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('operation_system_family', schema=None) as batch_op:
        batch_op.alter_column('string_slug',
               existing_type=app.models.datatypes.LimitedLengthString(length=80),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.add_column(sa.Column('icon', sa.VARCHAR(length=30), nullable=True))
        batch_op.drop_column('icon_number')
        batch_op.drop_column('icon_class')

    with op.batch_alter_table('note_importance', schema=None) as batch_op:
        batch_op.alter_column('string_slug',
               existing_type=app.models.datatypes.LimitedLengthString(length=80),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_note_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('mitre_attack_technique', schema=None) as batch_op:
        batch_op.alter_column('string_slug',
               existing_type=app.models.datatypes.LimitedLengthString(length=80),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('mitre_attack_tactic', schema=None) as batch_op:
        batch_op.alter_column('string_slug',
               existing_type=app.models.datatypes.LimitedLengthString(length=80),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('mac_address_info', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    with op.batch_alter_table('issue_template', schema=None) as batch_op:
        batch_op.alter_column('string_slug',
               existing_type=app.models.datatypes.LimitedLengthString(length=80),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('issue_status', schema=None) as batch_op:
        batch_op.alter_column('string_slug',
               existing_type=app.models.datatypes.LimitedLengthString(length=80),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('host_status', schema=None) as batch_op:
        batch_op.alter_column('string_slug',
               existing_type=app.models.datatypes.LimitedLengthString(length=80),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('evidence_of_event_prevented', schema=None) as batch_op:
        batch_op.alter_column('string_slug',
               existing_type=app.models.datatypes.LimitedLengthString(length=80),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('evidence_of_event_detected', schema=None) as batch_op:
        batch_op.alter_column('string_slug',
               existing_type=app.models.datatypes.LimitedLengthString(length=80),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('device_vendor', schema=None) as batch_op:
        batch_op.alter_column('string_slug',
               existing_type=app.models.datatypes.LimitedLengthString(length=80),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('device_type', schema=None) as batch_op:
        batch_op.alter_column('string_slug',
               existing_type=app.models.datatypes.LimitedLengthString(length=80),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.drop_column('icon_number')
        batch_op.drop_column('icon_class')

    with op.batch_alter_table('device_model', schema=None) as batch_op:
        batch_op.alter_column('string_slug',
               existing_type=app.models.datatypes.LimitedLengthString(length=80),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('critical_vulnerability', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_critical_vulnerability_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('check_wordlist', schema=None) as batch_op:
        batch_op.alter_column('string_slug',
               existing_type=app.models.datatypes.LimitedLengthString(length=80),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('application_language', schema=None) as batch_op:
        batch_op.alter_column('string_slug',
               existing_type=app.models.datatypes.LimitedLengthString(length=80),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('access_protocol', schema=None) as batch_op:
        batch_op.alter_column('string_slug',
               existing_type=app.models.datatypes.LimitedLengthString(length=80),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    
    with op.batch_alter_table('global_settings', schema=None) as batch_op:
        batch_op.drop_column('authentication_method')
        batch_op.add_column(sa.Column('authentication_method', sa.VARCHAR(length=30),
                                      nullable=False, server_default=sa.text("'PASSWORD'")))
    
    authentication_method_enum = sa.Enum('PASSWORD', 'REQUEST_HEADER', name='authenticationmethodenum')
    authentication_method_enum.drop(op.get_bind())
    
    with op.batch_alter_table('project_additional_field', schema=None) as batch_op:
        batch_op.alter_column('string_slug',
               existing_type=app.models.datatypes.LimitedLengthString(length=80),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.drop_column('field_type')
        batch_op.add_column(sa.Column('field_type', sa.VARCHAR(length=30),
                                      nullable=False, server_default="TextAreaField"))
    
    project_additional_field_type_enum = sa.Enum("StringField", "TextAreaField", "IntegerField", "BooleanField",
                                                 "DateField", "WysiwygField", name='projectadditionalparameterfieldtype')
    project_additional_field_type_enum.drop(op.get_bind(), checkfirst=True)

    with op.batch_alter_table('network', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_network_icon_id_network_icon'), type_='foreignkey')
        batch_op.drop_column('icon_id')

    op.drop_table('host_by_label')
    with op.batch_alter_table('network_icon', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_network_icon_string_slug'))

    op.drop_table('network_icon')
    with op.batch_alter_table('host_label', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_host_label_string_slug'))

    op.drop_table('host_label')

    # ### end Alembic commands ###
