"""Добавлена связь проблем с хостами

Revision ID: 1b152f5874ee
Revises: 1c41edbf4f26
Create Date: 2025-05-10 19:01:35.387184

"""
from alembic import op
import sqlalchemy as sa
import app


# revision identifiers, used by Alembic.
revision = '1b152f5874ee'
down_revision = '1c41edbf4f26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issue_has_host',
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.Column('issue_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['host_id'], ['host.id'], name=op.f('fk_issue_has_host_host_id_host'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['issue_id'], ['issue.id'], name=op.f('fk_issue_has_host_issue_id_issue'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('host_id', 'issue_id', name=op.f('pk_issue_has_host'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('issue_has_host')
    # ### end Alembic commands ###
