"""Добавлены команды

Revision ID: 1c41edbf4f26
Revises: 671c329b7d0c
Create Date: 2025-05-08 18:33:25.283474

"""
from alembic import op
import sqlalchemy as sa
import app


# revision identifiers, used by Alembic.
revision = '1c41edbf4f26'
down_revision = '671c329b7d0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_has_team', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_user_has_team_role_id_project_role'), 'project_role', ['role_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_has_team', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_user_has_team_role_id_project_role'), type_='foreignkey')
        batch_op.drop_column('role_id')

    # ### end Alembic commands ###
