"""Добавлены поля архивирования

Revision ID: 3b99fb344302
Revises: 1b152f5874ee
Create Date: 2025-05-10 22:18:38.486837

"""
from alembic import op
import sqlalchemy as sa
import app


# revision identifiers, used by Alembic.
revision = '3b99fb344302'
down_revision = '1b152f5874ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_theme_style', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archived_main_color', sa.String(length=40), server_default='#a3a3a3', nullable=False))
        batch_op.add_column(sa.Column('archived_main_text_color', sa.String(length=40), server_default='#000000', nullable=False))
        batch_op.add_column(sa.Column('archived_secondary_main_color', sa.String(length=40), server_default='#7d7d7d', nullable=False))
        batch_op.add_column(sa.Column('archived_neightboring_main_color', sa.String(length=40), server_default='#ccb6b6', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_theme_style', schema=None) as batch_op:
        batch_op.drop_column('archived_neightboring_main_color')
        batch_op.drop_column('archived_secondary_main_color')
        batch_op.drop_column('archived_main_text_color')
        batch_op.drop_column('archived_main_color')

    # ### end Alembic commands ###
