"""Updates services - new json attribute

Revision ID: 3debb2b6d246
Revises: a8e7a2ec87f6
Create Date: 2025-08-13 07:20:47.868212

"""
from alembic import op
import sqlalchemy as sa
import app


# revision identifiers, used by Alembic.
revision = '3debb2b6d246'
down_revision = 'a8e7a2ec87f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.add_column(sa.Column('additional_attributes', app.models.datatypes.JSONType(), nullable=True))
        batch_op.add_column(sa.Column('ssl', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.drop_constraint(batch_op.f('fk_service_screenshot_http_id_file_data'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_service_screenshot_https_id_file_data'), type_='foreignkey')
        batch_op.drop_column('screenshot_https_id')
        batch_op.drop_column('screenshot_http_id')
        batch_op.drop_column('https_title')
        batch_op.drop_column('http_title')
    
    with op.batch_alter_table("host", schema=None) as batch_op:
        batch_op.add_column(sa.Column("ipidsequence_class", sa.String(70), server_default="", nullable=False))
        batch_op.add_column(sa.Column("ipidsequence_value", sa.String(70), server_default="", nullable=False))
    
    with op.batch_alter_table('global_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('authentication_method', sa.String(length=30), server_default='password', nullable=False))
        batch_op.add_column(sa.Column('authentication_request_header_name', sa.String(length=50), server_default='X-User-Login', nullable=False))
        batch_op.add_column(sa.Column('authentication_request_header_allow_registration', sa.Boolean(), server_default=sa.false(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.add_column(sa.Column('http_title', sa.VARCHAR(length=80), nullable=True))
        batch_op.add_column(sa.Column('https_title', sa.VARCHAR(length=80), nullable=True))
        batch_op.add_column(sa.Column('screenshot_http_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('screenshot_https_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_service_screenshot_https_id_file_data'), 'file_data', ['screenshot_https_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('fk_service_screenshot_http_id_file_data'), 'file_data', ['screenshot_http_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_column('additional_attributes')
        batch_op.drop_column('ssl')
    
    with op.batch_alter_table("host", schema=None) as batch_op:
        batch_op.drop_column("ipidsequence_class")
        batch_op.drop_column("ipidsequence_value")
    
    with op.batch_alter_table('global_settings', schema=None) as batch_op:
        batch_op.drop_column('authentication_request_header_name')
        batch_op.drop_column('authentication_method')
        batch_op.drop_column('authentication_request_header_allow_registration')
    
    # ### end Alembic commands ###
