"""admin and empty field for credentials

Revision ID: 461b632c17d7
Revises: 8b05c995a642
Create Date: 2026-03-05 16:40:48.067793

"""
from alembic import op
import sqlalchemy as sa
import app


# revision identifiers, used by Alembic.
revision = '461b632c17d7'
down_revision = '8b05c995a642'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credential', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), server_default=sa.false(), nullable=False))
        batch_op.add_column(sa.Column('is_empty', sa.Boolean(), server_default=sa.false(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credential', schema=None) as batch_op:
        batch_op.drop_column('is_empty')
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
