"""Added host interfaces

Revision ID: 464958bad06e
Revises: f19d0ae7f1e4
Create Date: 2025-02-12 16:49:14.875170

"""
from alembic import op
import sqlalchemy as sa
import app


# revision identifiers, used by Alembic.
revision = '464958bad06e'
down_revision = 'f19d0ae7f1e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('by_template_slug', sa.String(), nullable=True))

    with op.batch_alter_table('project_task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('by_template_slug', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_task', schema=None) as batch_op:
        batch_op.drop_column('by_template_slug')

    with op.batch_alter_table('issue', schema=None) as batch_op:
        batch_op.drop_column('by_template_slug')

    # ### end Alembic commands ###
