"""Initial migrate

Revision ID: 4c8c3586aa6e
Revises: 
Create Date: 2025-02-08 19:55:12.579368

"""
from alembic import op
import sqlalchemy as sa
import app


# revision identifiers, used by Alembic.
revision = '4c8c3586aa6e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_protocol',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('string_slug', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=30), nullable=False),
    sa.Column('comment', app.models.datatypes.LimitedLengthString(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_access_protocol'))
    )
    with op.batch_alter_table('access_protocol', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_access_protocol_string_slug'), ['string_slug'], unique=True)

    op.create_table('application_language',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('string_slug', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=10), nullable=False),
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_application_language'))
    )
    with op.batch_alter_table('application_language', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_application_language_string_slug'), ['string_slug'], unique=True)

    op.create_table('background_task_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=250), nullable=False),
    sa.Column('module_name', sa.String(length=50), nullable=False),
    sa.Column('inner_name', sa.String(length=50), nullable=False),
    sa.Column('inner_value', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_background_task_options'))
    )
    op.create_table('check_wordlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('string_slug', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=40), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_check_wordlist'))
    )
    with op.batch_alter_table('check_wordlist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_check_wordlist_string_slug'), ['string_slug'], unique=True)

    op.create_table('device_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('string_slug', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('nmap_name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_device_type'))
    )
    with op.batch_alter_table('device_type', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_type_string_slug'), ['string_slug'], unique=True)

    op.create_table('device_vendor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('string_slug', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_device_vendor'))
    )
    with op.batch_alter_table('device_vendor', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_vendor_string_slug'), ['string_slug'], unique=True)

    op.create_table('file_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.Column('extension', sa.String(length=4), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('directory_id', sa.Integer(), nullable=True),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], name=op.f('fk_file_data_created_by_id_user'), ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['directory_id'], ['file_directory.id'], name=op.f('fk_file_data_directory_id_file_directory'), ondelete='CASCADE', use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_file_data'))
    )
    op.create_table('hash_prototype',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('regex', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hash_prototype'))
    )
    with op.batch_alter_table('hash_prototype', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hash_prototype_regex'), ['regex'], unique=True)

    op.create_table('hash_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('string_slug', app.models.datatypes.LimitedLengthString(length=80), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('hashcat_mode', sa.String(length=20), nullable=True),
    sa.Column('john_mode', sa.String(length=40), nullable=True),
    sa.Column('is_popular', sa.Boolean(), nullable=False),
    sa.Column('extended', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hash_type'))
    )
    with op.batch_alter_table('hash_type', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hash_type_string_slug'), ['string_slug'], unique=True)

    op.create_table('host_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('string_slug', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_host_status'))
    )
    with op.batch_alter_table('host_status', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_host_status_string_slug'), ['string_slug'], unique=True)

    op.create_table('issue_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('string_slug', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=40), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('color', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_issue_status'))
    )
    with op.batch_alter_table('issue_status', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_issue_status_string_slug'), ['string_slug'], unique=True)

    op.create_table('mac_address_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('mac_prefix', sa.String(length=14), nullable=False),
    sa.Column('is_private', sa.Boolean(), nullable=False),
    sa.Column('block_type', sa.String(length=4), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mac_address_info')),
    sa.UniqueConstraint('mac_prefix', name=op.f('uq_mac_address_info_mac_prefix'))
    )
    op.create_table('note_importance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('string_slug', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=40), nullable=False),
    sa.Column('color', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_note_importance'))
    )
    with op.batch_alter_table('note_importance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_note_importance_string_slug'), ['string_slug'], unique=True)

    op.create_table('operation_system_family',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('string_slug', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_operation_system_family'))
    )
    with op.batch_alter_table('operation_system_family', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_operation_system_family_string_slug'), ['string_slug'], unique=True)

    op.create_table('programming_language_class',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('string_slug', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_programming_language_class'))
    )
    with op.batch_alter_table('programming_language_class', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_programming_language_class_string_slug'), ['string_slug'], unique=True)

    op.create_table('programming_language_theme',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('string_slug', sa.String(length=50), nullable=False),
    sa.Column('directory', sa.String(length=30), nullable=False),
    sa.Column('filename', sa.String(length=50), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_programming_language_theme'))
    )
    with op.batch_alter_table('programming_language_theme', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_programming_language_theme_string_slug'), ['string_slug'], unique=True)

    op.create_table('project_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('string_slug', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=35), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_role'))
    )
    with op.batch_alter_table('project_role', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_role_string_slug'), ['string_slug'], unique=True)

    op.create_table('project_task_priority',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('string_slug', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('color', sa.String(length=60), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_task_priority'))
    )
    with op.batch_alter_table('project_task_priority', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_task_priority_string_slug'), ['string_slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_project_task_priority_title'), ['title'], unique=False)

    op.create_table('project_task_tracker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('string_slug', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=35), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_task_tracker'))
    )
    with op.batch_alter_table('project_task_tracker', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_task_tracker_string_slug'), ['string_slug'], unique=True)

    op.create_table('service_port_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('string_slug', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_service_port_state'))
    )
    with op.batch_alter_table('service_port_state', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_port_state_string_slug'), ['string_slug'], unique=True)

    op.create_table('service_transport_level_protocol',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('string_slug', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_service_transport_level_protocol'))
    )
    with op.batch_alter_table('service_transport_level_protocol', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_transport_level_protocol_string_slug'), ['string_slug'], unique=True)

    op.create_table('task_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('string_slug', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=20), nullable=False),
    sa.Column('color', sa.String(length=60), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('icon', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task_state'))
    )
    with op.batch_alter_table('task_state', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_state_string_slug'), ['string_slug'], unique=True)

    op.create_table('user_position',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=35), nullable=False),
    sa.Column('string_slug', sa.String(length=50), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_position'))
    )
    with op.batch_alter_table('user_position', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_position_string_slug'), ['string_slug'], unique=True)

    op.create_table('user_theme_style',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('string_slug', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=40), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('main_color', sa.String(length=60), nullable=False),
    sa.Column('neightboring_main_color', sa.String(length=60), nullable=False),
    sa.Column('secondary_main_color', sa.String(length=60), nullable=False),
    sa.Column('main_text_color', sa.String(length=60), nullable=False),
    sa.Column('hovering_main_element_color', sa.String(length=60), nullable=False),
    sa.Column('sidebar_background_color', sa.String(length=60), nullable=False),
    sa.Column('main_content_background_color', sa.String(length=60), nullable=False),
    sa.Column('color_card_background_header', sa.String(length=60), nullable=False),
    sa.Column('color_chats_hour', sa.String(length=40), nullable=False),
    sa.Column('color_chats_my_message', sa.String(length=40), nullable=False),
    sa.Column('color_chats_my_message_text', sa.String(length=40), nullable=False),
    sa.Column('color_chats_other_message', sa.String(length=40), nullable=False),
    sa.Column('color_chats_other_message_text', sa.String(length=40), nullable=False),
    sa.Column('bs_card_color', sa.String(length=40), nullable=False),
    sa.Column('fixed_sidebar', sa.Boolean(), nullable=False),
    sa.Column('sidebar_position_left', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_theme_style'))
    )
    with op.batch_alter_table('user_theme_style', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_theme_style_string_slug'), ['string_slug'], unique=True)

    op.create_table('vulnerable_environment_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('string_slug', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vulnerable_environment_type'))
    )
    with op.batch_alter_table('vulnerable_environment_type', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vulnerable_environment_type_string_slug'), ['string_slug'], unique=True)

    op.create_table('default_port_and_transport_proto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=20), nullable=True),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('transport_level_protocol_id', sa.Integer(), nullable=True),
    sa.Column('access_protocol_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['access_protocol_id'], ['access_protocol.id'], name=op.f('fk_default_port_and_transport_proto_access_protocol_id_access_protocol'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transport_level_protocol_id'], ['service_transport_level_protocol.id'], name=op.f('fk_default_port_and_transport_proto_transport_level_protocol_id_service_transport_level_protocol'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_default_port_and_transport_proto'))
    )
    op.create_table('device_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('string_slug', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('device_type_id', sa.Integer(), nullable=True),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['device_type_id'], ['device_type.id'], name=op.f('fk_device_model_device_type_id_device_type'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vendor_id'], ['device_vendor.id'], name=op.f('fk_device_model_vendor_id_device_vendor'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_device_model'))
    )
    with op.batch_alter_table('device_model', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_model_string_slug'), ['string_slug'], unique=True)

    op.create_table('global_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('main_page_name', sa.String(length=50), nullable=False),
    sa.Column('text_main_page', sa.String(), nullable=False),
    sa.Column('default_language_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['default_language_id'], ['application_language.id'], name=op.f('fk_global_settings_default_language_id_application_language'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_global_settings'))
    )
    op.create_table('hash_type_has_prototype',
    sa.Column('hash_id', sa.Integer(), nullable=False),
    sa.Column('prototype_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hash_id'], ['hash_type.id'], name=op.f('fk_hash_type_has_prototype_hash_id_hash_type')),
    sa.ForeignKeyConstraint(['prototype_id'], ['hash_prototype.id'], name=op.f('fk_hash_type_has_prototype_prototype_id_hash_prototype')),
    sa.PrimaryKeyConstraint('hash_id', 'prototype_id', name=op.f('pk_hash_type_has_prototype'))
    )
    op.create_table('programming_language',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=40), nullable=False),
    sa.Column('string_slug', sa.String(length=50), nullable=False),
    sa.Column('alias', sa.String(length=20), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('language_class_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['language_class_id'], ['programming_language_class.id'], name=op.f('fk_programming_language_language_class_id_programming_language_class'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_programming_language')),
    sa.UniqueConstraint('alias', name=op.f('uq_programming_language_alias')),
    sa.UniqueConstraint('title', name=op.f('uq_programming_language_title'))
    )
    with op.batch_alter_table('programming_language', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_programming_language_string_slug'), ['string_slug'], unique=True)

    op.create_table('project_report_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['file_data.id'], name=op.f('fk_project_report_template_template_id_file_data'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_report_template'))
    )
    op.create_table('project_task_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('string_slug', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('task_title', sa.String(length=30), nullable=False),
    sa.Column('task_description', sa.String(), nullable=False),
    sa.Column('task_tracker_id', sa.Integer(), nullable=True),
    sa.Column('task_priority_id', sa.Integer(), nullable=True),
    sa.Column('task_estimation_time_cost', sa.Interval(), nullable=True),
    sa.ForeignKeyConstraint(['task_priority_id'], ['project_task_priority.id'], name=op.f('fk_project_task_template_task_priority_id_project_task_priority'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_tracker_id'], ['project_task_tracker.id'], name=op.f('fk_project_task_template_task_tracker_id_project_task_tracker'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_task_template'))
    )
    with op.batch_alter_table('project_task_template', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_task_template_string_slug'), ['string_slug'], unique=True)

    op.create_table('role_has_project_object_action',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('object_class_name', sa.String(length=15), nullable=False),
    sa.Column('action', sa.String(length=15), nullable=False),
    sa.Column('is_granted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['project_role.id'], name=op.f('fk_role_has_project_object_action_role_id_project_role'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_role_has_project_object_action')),
    sa.UniqueConstraint('role_id', 'object_class_name', 'action', name='unique_role_object_class_and_action_together')
    )
    op.create_table('state_to_state_task',
    sa.Column('from_state_id', sa.Integer(), nullable=False),
    sa.Column('to_state_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['from_state_id'], ['task_state.id'], name=op.f('fk_state_to_state_task_from_state_id_task_state')),
    sa.ForeignKeyConstraint(['to_state_id'], ['task_state.id'], name=op.f('fk_state_to_state_task_to_state_id_task_state')),
    sa.PrimaryKeyConstraint('from_state_id', 'to_state_id', name=op.f('pk_state_to_state_task'))
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('string_slug', sa.String(length=20), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('login', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=170), nullable=False),
    sa.Column('email', sa.String(length=30), nullable=True),
    sa.Column('first_name', sa.String(length=20), nullable=False),
    sa.Column('last_name', sa.String(length=30), nullable=False),
    sa.Column('middle_name', sa.String(length=30), nullable=False),
    sa.Column('is_administrator', sa.Boolean(), nullable=False),
    sa.Column('avatar_id', sa.Integer(), nullable=True),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('position_id', sa.Integer(), nullable=True),
    sa.Column('programming_language_theme_id', sa.Integer(), nullable=True),
    sa.Column('theme_style_id', sa.Integer(), nullable=True),
    sa.Column('token', sa.String(length=60), nullable=False),
    sa.Column('token_expiration', sa.DateTime(), nullable=False),
    sa.Column('preferred_language_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['avatar_id'], ['file_data.id'], name=op.f('fk_user_avatar_id_file_data'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['manager_id'], ['user.id'], name=op.f('fk_user_manager_id_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['position_id'], ['user_position.id'], name=op.f('fk_user_position_id_user_position'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['preferred_language_id'], ['application_language.id'], name=op.f('fk_user_preferred_language_id_application_language'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['programming_language_theme_id'], ['programming_language_theme.id'], name=op.f('fk_user_programming_language_theme_id_programming_language_theme'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['theme_style_id'], ['user_theme_style.id'], name=op.f('fk_user_theme_style_id_user_theme_style'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user'))
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_login'), ['login'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_string_slug'), ['string_slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_token'), ['token'], unique=True)

    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('to_object_type', sa.String(length=30), nullable=False),
    sa.Column('to_object_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('reply_to_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], name=op.f('fk_comment_created_by_id_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reply_to_id'], ['comment.id'], name=op.f('fk_comment_reply_to_id_comment'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_comment'))
    )
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comment_to_object_type'), ['to_object_type'], unique=False)

    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('start_at', sa.Date(), nullable=False),
    sa.Column('end_at', sa.Date(), nullable=False),
    sa.Column('leader_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], name=op.f('fk_project_created_by_id_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['leader_id'], ['user.id'], name=op.f('fk_project_leader_id_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['user.id'], name=op.f('fk_project_updated_by_id_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project'))
    )
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_title'), ['title'], unique=False)

    op.create_table('proof_of_concept',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('string_slug', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('source_code', sa.String(), nullable=False),
    sa.Column('source_code_language_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['source_code_language_id'], ['programming_language.id'], name=op.f('fk_proof_of_concept_source_code_language_id_programming_language'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_proof_of_concept')),
    sa.UniqueConstraint('string_slug', name=op.f('uq_proof_of_concept_string_slug'))
    )
    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=30), nullable=False),
    sa.Column('string_slug', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('leader_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['leader_id'], ['user.id'], name=op.f('fk_team_leader_id_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_team'))
    )
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_string_slug'), ['string_slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_team_title'), ['title'], unique=False)

    op.create_table('user_environment_setting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('to_user_id', sa.Integer(), nullable=False),
    sa.Column('sidebar_hide', sa.Boolean(), nullable=False),
    sa.Column('comment_order_asc', sa.Boolean(), nullable=False),
    sa.Column('comment_reply_padding', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['to_user_id'], ['user.id'], name=op.f('fk_user_environment_setting_to_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_environment_setting')),
    sa.UniqueConstraint('to_user_id', name=op.f('uq_user_environment_setting_to_user_id'))
    )
    op.create_table('user_has_program_language',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('programming_language_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['programming_language_id'], ['programming_language.id'], name=op.f('fk_user_has_program_language_programming_language_id_programming_language'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_user_has_program_language_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'programming_language_id', name=op.f('pk_user_has_program_language'))
    )
    op.create_table('user_notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('to_user_id', sa.Integer(), nullable=False),
    sa.Column('by_user_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('technical_info', app.models.datatypes.JSONType(), nullable=True),
    sa.Column('link_to_object', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['by_user_id'], ['user.id'], name=op.f('fk_user_notification_by_user_id_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['to_user_id'], ['user.id'], name=op.f('fk_user_notification_to_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_notification'))
    )
    op.create_table('wiki_directory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=150), nullable=True),
    sa.Column('parent_directory_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], name=op.f('fk_wiki_directory_created_by_id_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_directory_id'], ['wiki_directory.id'], name=op.f('fk_wiki_directory_parent_directory_id_wiki_directory'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['user.id'], name=op.f('fk_wiki_directory_updated_by_id_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wiki_directory'))
    )
    op.create_table('chat_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], name=op.f('fk_chat_message_created_by_id_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('fk_chat_message_project_id_project'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_message'))
    )
    op.create_table('credential',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('login', sa.String(length=40), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('hash_type_id', sa.Integer(), nullable=True),
    sa.Column('check_wordlist_id', sa.Integer(), nullable=True),
    sa.Column('password', sa.String(length=70), nullable=False),
    sa.Column('is_pentest_credentials', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['check_wordlist_id'], ['check_wordlist.id'], name=op.f('fk_credential_check_wordlist_id_check_wordlist'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], name=op.f('fk_credential_created_by_id_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['hash_type_id'], ['hash_type.id'], name=op.f('fk_credential_hash_type_id_hash_type'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('fk_credential_project_id_project'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['user.id'], name=op.f('fk_credential_updated_by_id_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_credential'))
    )
    with op.batch_alter_table('credential', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_credential_is_pentest_credentials'), ['is_pentest_credentials'], unique=False)

    op.create_table('file_directory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('parent_dir_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], name=op.f('fk_file_directory_created_by_id_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_dir_id'], ['file_directory.id'], name=op.f('fk_file_directory_parent_dir_id_file_directory'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('fk_file_directory_project_id_project'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['user.id'], name=op.f('fk_file_directory_updated_by_id_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_file_directory'))
    )
    op.create_table('network',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('title', sa.String(length=40), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('ip_address', app.models.datatypes.NetworkAddress(length=50), nullable=False),
    sa.Column('internal_ip', app.models.datatypes.NetworkAddress(length=50), nullable=True),
    sa.Column('asn', sa.String(length=20), nullable=True),
    sa.Column('connect_cmd', sa.String(length=50), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], name=op.f('fk_network_created_by_id_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('fk_network_project_id_project'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['user.id'], name=op.f('fk_network_updated_by_id_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_network')),
    sa.UniqueConstraint('project_id', 'ip_address', name='_unique_ip_and_project_together')
    )
    op.create_table('note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('importance_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], name=op.f('fk_note_created_by_id_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['importance_id'], ['note_importance.id'], name=op.f('fk_note_importance_id_note_importance'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('fk_note_project_id_project'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['user.id'], name=op.f('fk_note_updated_by_id_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_note'))
    )
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_note_created_at'), ['created_at'], unique=False)

    op.create_table('project_task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('title', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('tracker_id', sa.Integer(), nullable=True),
    sa.Column('priority_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('state_id', sa.Integer(), nullable=True),
    sa.Column('assigned_to_id', sa.Integer(), nullable=True),
    sa.Column('date_start', sa.Date(), nullable=True),
    sa.Column('date_end', sa.Date(), nullable=True),
    sa.Column('readiness', sa.SmallInteger(), nullable=False),
    sa.Column('parent_task_id', sa.Integer(), nullable=True),
    sa.Column('estimation_time_cost', sa.Interval(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['user.id'], name=op.f('fk_project_task_assigned_to_id_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], name=op.f('fk_project_task_created_by_id_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_task_id'], ['project_task.id'], name=op.f('fk_project_task_parent_task_id_project_task'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['priority_id'], ['project_task_priority.id'], name=op.f('fk_project_task_priority_id_project_task_priority'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('fk_project_task_project_id_project'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['state_id'], ['task_state.id'], name=op.f('fk_project_task_state_id_task_state'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tracker_id'], ['project_task_tracker.id'], name=op.f('fk_project_task_tracker_id_project_task_tracker'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['user.id'], name=op.f('fk_project_task_updated_by_id_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_task'))
    )
    op.create_table('reaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_positive', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('to_comment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], name=op.f('fk_reaction_created_by_id_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['to_comment_id'], ['comment.id'], name=op.f('fk_reaction_to_comment_id_comment'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reaction'))
    )
    op.create_table('user_has_team',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], name=op.f('fk_user_has_team_team_id_team'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_user_has_team_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'team_id', name=op.f('pk_user_has_team'))
    )
    op.create_table('user_role_has_project',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('fk_user_role_has_project_project_id_project'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['project_role.id'], name=op.f('fk_user_role_has_project_role_id_project_role'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_user_role_has_project_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'project_id', 'role_id', name=op.f('pk_user_role_has_project'))
    )
    op.create_table('wiki_page',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=150), nullable=True),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('directory_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], name=op.f('fk_wiki_page_created_by_id_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['directory_id'], ['wiki_directory.id'], name=op.f('fk_wiki_page_directory_id_wiki_directory'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['user.id'], name=op.f('fk_wiki_page_updated_by_id_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wiki_page'))
    )
    op.create_table('credential_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('changes', app.models.datatypes.JSONType(), nullable=True),
    sa.Column('to_object_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], name=op.f('fk_credential_history_created_by_id_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['to_object_id'], ['credential.id'], name=op.f('fk_credential_history_to_object_id_credential'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_credential_history'))
    )
    op.create_table('critical_vulnerability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('identifier', sa.String(length=20), nullable=False),
    sa.Column('cvss', sa.Float(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('vulnerable_environment_type_id', sa.Integer(), nullable=True),
    sa.Column('vulnerable_environment', sa.String(), nullable=True),
    sa.Column('proof_of_concept_language_id', sa.Integer(), nullable=True),
    sa.Column('proof_of_concept_code', sa.String(), nullable=True),
    sa.Column('wikipage_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], name=op.f('fk_critical_vulnerability_created_by_id_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['proof_of_concept_language_id'], ['programming_language.id'], name=op.f('fk_critical_vulnerability_proof_of_concept_language_id_programming_language'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['user.id'], name=op.f('fk_critical_vulnerability_updated_by_id_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vulnerable_environment_type_id'], ['vulnerable_environment_type.id'], name=op.f('fk_critical_vulnerability_vulnerable_environment_type_id_vulnerable_environment_type'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['wikipage_id'], ['wiki_page.id'], name=op.f('fk_critical_vulnerability_wikipage_id_wiki_page'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_critical_vulnerability')),
    sa.UniqueConstraint('year', 'identifier', name='_unique_year_and_identifier_together')
    )
    with op.batch_alter_table('critical_vulnerability', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_critical_vulnerability_created_at'), ['created_at'], unique=False)

    op.create_table('file_has_task',
    sa.Column('filedata_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['filedata_id'], ['file_data.id'], name=op.f('fk_file_has_task_filedata_id_file_data'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['project_task.id'], name=op.f('fk_file_has_task_task_id_project_task'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('filedata_id', 'task_id', name=op.f('pk_file_has_task'))
    )
    op.create_table('host',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('technical', sa.String(), nullable=True),
    sa.Column('state_id', sa.Integer(), nullable=True),
    sa.Column('state_reason', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('ip_address', app.models.datatypes.IPAddress(length=20), nullable=False),
    sa.Column('mac', sa.String(length=17), nullable=True),
    sa.Column('mac_info_id', sa.Integer(), nullable=True),
    sa.Column('operation_system_family_id', sa.Integer(), nullable=True),
    sa.Column('operation_system_gen', sa.String(length=30), nullable=True),
    sa.Column('from_network_id', sa.Integer(), nullable=False),
    sa.Column('device_type_id', sa.Integer(), nullable=True),
    sa.Column('device_vendor_id', sa.Integer(), nullable=True),
    sa.Column('device_model_id', sa.Integer(), nullable=True),
    sa.Column('excluded', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], name=op.f('fk_host_created_by_id_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['device_model_id'], ['device_model.id'], name=op.f('fk_host_device_model_id_device_model'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['device_type_id'], ['device_type.id'], name=op.f('fk_host_device_type_id_device_type'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['device_vendor_id'], ['device_vendor.id'], name=op.f('fk_host_device_vendor_id_device_vendor'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['from_network_id'], ['network.id'], name=op.f('fk_host_from_network_id_network'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mac_info_id'], ['mac_address_info.id'], name=op.f('fk_host_mac_info_id_mac_address_info'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['operation_system_family_id'], ['operation_system_family.id'], name=op.f('fk_host_operation_system_family_id_operation_system_family'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['state_id'], ['host_status.id'], name=op.f('fk_host_state_id_host_status'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['user.id'], name=op.f('fk_host_updated_by_id_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_host')),
    sa.UniqueConstraint('from_network_id', 'ip_address', name='_unique_ip_and_network_together')
    )
    op.create_table('network_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('changes', app.models.datatypes.JSONType(), nullable=True),
    sa.Column('to_object_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], name=op.f('fk_network_history_created_by_id_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['to_object_id'], ['network.id'], name=op.f('fk_network_history_to_object_id_network'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_network_history'))
    )
    op.create_table('observers_to_task',
    sa.Column('observer_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['observer_id'], ['user.id'], name=op.f('fk_observers_to_task_observer_id_user'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['project_task.id'], name=op.f('fk_observers_to_task_task_id_project_task'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('observer_id', 'task_id', name=op.f('pk_observers_to_task'))
    )
    op.create_table('project_task_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('changes', app.models.datatypes.JSONType(), nullable=True),
    sa.Column('to_object_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], name=op.f('fk_project_task_history_created_by_id_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['to_object_id'], ['project_task.id'], name=op.f('fk_project_task_history_to_object_id_project_task'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_task_history'))
    )
    op.create_table('task_related_to_task',
    sa.Column('first_related_task_id', sa.Integer(), nullable=False),
    sa.Column('second_related_task_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['first_related_task_id'], ['project_task.id'], name=op.f('fk_task_related_to_task_first_related_task_id_project_task'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['second_related_task_id'], ['project_task.id'], name=op.f('fk_task_related_to_task_second_related_task_id_project_task'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('first_related_task_id', 'second_related_task_id', name=op.f('pk_task_related_to_task'))
    )
    op.create_table('critical_vulnerability_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('changes', app.models.datatypes.JSONType(), nullable=True),
    sa.Column('to_object_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], name=op.f('fk_critical_vulnerability_history_created_by_id_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['to_object_id'], ['critical_vulnerability.id'], name=op.f('fk_critical_vulnerability_history_to_object_id_critical_vulnerability'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_critical_vulnerability_history'))
    )
    op.create_table('host_dns_name',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('dns_type', sa.String(length=8), nullable=True),
    sa.Column('to_host_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['to_host_id'], ['host.id'], name=op.f('fk_host_dns_name_to_host_id_host'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_host_dns_name')),
    sa.UniqueConstraint('to_host_id', 'title', 'dns_type', name='_unique_host_title_and_dns_type_together')
    )
    op.create_table('host_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('changes', app.models.datatypes.JSONType(), nullable=True),
    sa.Column('to_object_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], name=op.f('fk_host_history_created_by_id_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['to_object_id'], ['host.id'], name=op.f('fk_host_history_to_object_id_host'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_host_history'))
    )
    op.create_table('issue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('fix', sa.String(), nullable=True),
    sa.Column('technical', sa.String(), nullable=True),
    sa.Column('riscs', sa.String(), nullable=True),
    sa.Column('references', sa.String(), nullable=True),
    sa.Column('cvss', sa.Float(), nullable=True),
    sa.Column('cve_id', sa.Integer(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('proof_of_concept_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], name=op.f('fk_issue_created_by_id_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['cve_id'], ['critical_vulnerability.id'], name=op.f('fk_issue_cve_id_critical_vulnerability'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('fk_issue_project_id_project'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['proof_of_concept_id'], ['proof_of_concept.id'], name=op.f('fk_issue_proof_of_concept_id_proof_of_concept'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['status_id'], ['issue_status.id'], name=op.f('fk_issue_status_id_issue_status'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['user.id'], name=op.f('fk_issue_updated_by_id_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_issue'))
    )
    op.create_table('issue_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('string_slug', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('issue_title', sa.String(length=50), nullable=False),
    sa.Column('issue_description', sa.String(), nullable=False),
    sa.Column('issue_fix', sa.String(), nullable=True),
    sa.Column('issue_technical', sa.String(), nullable=True),
    sa.Column('issue_riscs', sa.String(), nullable=True),
    sa.Column('issue_references', sa.String(), nullable=True),
    sa.Column('issue_cvss', sa.Float(), nullable=True),
    sa.Column('issue_cve_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['issue_cve_id'], ['critical_vulnerability.id'], name=op.f('fk_issue_template_issue_cve_id_critical_vulnerability'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_issue_template'))
    )
    with op.batch_alter_table('issue_template', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_issue_template_string_slug'), ['string_slug'], unique=True)

    op.create_table('service',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('title', sa.String(length=60), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('technical', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('access_protocol_id', sa.Integer(), nullable=True),
    sa.Column('port_state_id', sa.Integer(), nullable=True),
    sa.Column('port_state_reason', sa.String(), nullable=False),
    sa.Column('transport_level_protocol_id', sa.Integer(), nullable=True),
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.Column('screenshot_http_id', sa.Integer(), nullable=True),
    sa.Column('screenshot_https_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['access_protocol_id'], ['access_protocol.id'], name=op.f('fk_service_access_protocol_id_access_protocol'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], name=op.f('fk_service_created_by_id_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['host_id'], ['host.id'], name=op.f('fk_service_host_id_host'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['port_state_id'], ['service_port_state.id'], name=op.f('fk_service_port_state_id_service_port_state'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['screenshot_http_id'], ['file_data.id'], name=op.f('fk_service_screenshot_http_id_file_data'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['screenshot_https_id'], ['file_data.id'], name=op.f('fk_service_screenshot_https_id_file_data'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['transport_level_protocol_id'], ['service_transport_level_protocol.id'], name=op.f('fk_service_transport_level_protocol_id_service_transport_level_protocol'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['user.id'], name=op.f('fk_service_updated_by_id_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_service')),
    sa.UniqueConstraint('host_id', 'port', 'transport_level_protocol_id', name='_unique_host_port_and_transport_protocol')
    )
    op.create_table('credential_by_service',
    sa.Column('credential_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['credential_id'], ['credential.id'], name=op.f('fk_credential_by_service_credential_id_credential')),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], name=op.f('fk_credential_by_service_service_id_service')),
    sa.PrimaryKeyConstraint('credential_id', 'service_id', name=op.f('pk_credential_by_service'))
    )
    op.create_table('issue_has_service',
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('issue_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['issue_id'], ['issue.id'], name=op.f('fk_issue_has_service_issue_id_issue'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], name=op.f('fk_issue_has_service_service_id_service'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('service_id', 'issue_id', name=op.f('pk_issue_has_service'))
    )
    op.create_table('issue_has_task',
    sa.Column('issue_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['issue_id'], ['issue.id'], name=op.f('fk_issue_has_task_issue_id_issue'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['project_task.id'], name=op.f('fk_issue_has_task_task_id_project_task'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('issue_id', 'task_id', name=op.f('pk_issue_has_task'))
    )
    op.create_table('issue_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('changes', app.models.datatypes.JSONType(), nullable=True),
    sa.Column('to_object_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], name=op.f('fk_issue_history_created_by_id_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['to_object_id'], ['issue.id'], name=op.f('fk_issue_history_to_object_id_issue'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_issue_history'))
    )
    op.create_table('service_has_task',
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], name=op.f('fk_service_has_task_service_id_service'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['project_task.id'], name=op.f('fk_service_has_task_task_id_project_task'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('service_id', 'task_id', name=op.f('pk_service_has_task'))
    )
    op.create_table('service_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('changes', app.models.datatypes.JSONType(), nullable=True),
    sa.Column('to_object_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], name=op.f('fk_service_history_created_by_id_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['to_object_id'], ['service.id'], name=op.f('fk_service_history_to_object_id_service'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_service_history'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('service_history')
    op.drop_table('service_has_task')
    op.drop_table('issue_history')
    op.drop_table('issue_has_task')
    op.drop_table('issue_has_service')
    op.drop_table('credential_by_service')
    op.drop_table('service')
    with op.batch_alter_table('issue_template', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_issue_template_string_slug'))

    op.drop_table('issue_template')
    op.drop_table('issue')
    op.drop_table('host_history')
    op.drop_table('host_dns_name')
    op.drop_table('critical_vulnerability_history')
    op.drop_table('task_related_to_task')
    op.drop_table('project_task_history')
    op.drop_table('observers_to_task')
    op.drop_table('network_history')
    op.drop_table('host')
    op.drop_table('file_has_task')
    with op.batch_alter_table('critical_vulnerability', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_critical_vulnerability_created_at'))

    op.drop_table('critical_vulnerability')
    op.drop_table('credential_history')
    op.drop_table('wiki_page')
    op.drop_table('user_role_has_project')
    op.drop_table('user_has_team')
    op.drop_table('reaction')
    op.drop_table('project_task')
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_note_created_at'))

    op.drop_table('note')
    op.drop_table('network')
    op.drop_table('file_directory')
    with op.batch_alter_table('credential', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_credential_is_pentest_credentials'))

    op.drop_table('credential')
    op.drop_table('chat_message')
    op.drop_table('wiki_directory')
    op.drop_table('user_notification')
    op.drop_table('user_has_program_language')
    op.drop_table('user_environment_setting')
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_title'))
        batch_op.drop_index(batch_op.f('ix_team_string_slug'))

    op.drop_table('team')
    op.drop_table('proof_of_concept')
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_title'))
        batch_op.drop_index(batch_op.f('ix_project_created_at'))

    op.drop_table('project')
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comment_to_object_type'))

    op.drop_table('comment')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_token'))
        batch_op.drop_index(batch_op.f('ix_user_string_slug'))
        batch_op.drop_index(batch_op.f('ix_user_login'))

    op.drop_table('user')
    op.drop_table('state_to_state_task')
    op.drop_table('role_has_project_object_action')
    with op.batch_alter_table('project_task_template', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_task_template_string_slug'))

    op.drop_table('project_task_template')
    op.drop_table('project_report_template')
    with op.batch_alter_table('programming_language', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_programming_language_string_slug'))

    op.drop_table('programming_language')
    op.drop_table('hash_type_has_prototype')
    op.drop_table('global_settings')
    with op.batch_alter_table('device_model', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_model_string_slug'))

    op.drop_table('device_model')
    op.drop_table('default_port_and_transport_proto')
    with op.batch_alter_table('vulnerable_environment_type', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vulnerable_environment_type_string_slug'))

    op.drop_table('vulnerable_environment_type')
    with op.batch_alter_table('user_theme_style', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_theme_style_string_slug'))

    op.drop_table('user_theme_style')
    with op.batch_alter_table('user_position', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_position_string_slug'))

    op.drop_table('user_position')
    with op.batch_alter_table('task_state', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_state_string_slug'))

    op.drop_table('task_state')
    with op.batch_alter_table('service_transport_level_protocol', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_transport_level_protocol_string_slug'))

    op.drop_table('service_transport_level_protocol')
    with op.batch_alter_table('service_port_state', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_port_state_string_slug'))

    op.drop_table('service_port_state')
    with op.batch_alter_table('project_task_tracker', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_task_tracker_string_slug'))

    op.drop_table('project_task_tracker')
    with op.batch_alter_table('project_task_priority', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_task_priority_title'))
        batch_op.drop_index(batch_op.f('ix_project_task_priority_string_slug'))

    op.drop_table('project_task_priority')
    with op.batch_alter_table('project_role', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_role_string_slug'))

    op.drop_table('project_role')
    with op.batch_alter_table('programming_language_theme', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_programming_language_theme_string_slug'))

    op.drop_table('programming_language_theme')
    with op.batch_alter_table('programming_language_class', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_programming_language_class_string_slug'))

    op.drop_table('programming_language_class')
    with op.batch_alter_table('operation_system_family', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_operation_system_family_string_slug'))

    op.drop_table('operation_system_family')
    with op.batch_alter_table('note_importance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_note_importance_string_slug'))

    op.drop_table('note_importance')
    op.drop_table('mac_address_info')
    with op.batch_alter_table('issue_status', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_issue_status_string_slug'))

    op.drop_table('issue_status')
    with op.batch_alter_table('host_status', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_host_status_string_slug'))

    op.drop_table('host_status')
    with op.batch_alter_table('hash_type', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hash_type_string_slug'))

    op.drop_table('hash_type')
    with op.batch_alter_table('hash_prototype', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hash_prototype_regex'))

    op.drop_table('hash_prototype')
    op.drop_table('file_data')
    with op.batch_alter_table('device_vendor', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_vendor_string_slug'))

    op.drop_table('device_vendor')
    with op.batch_alter_table('device_type', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_type_string_slug'))

    op.drop_table('device_type')
    with op.batch_alter_table('check_wordlist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_check_wordlist_string_slug'))

    op.drop_table('check_wordlist')
    op.drop_table('background_task_options')
    with op.batch_alter_table('application_language', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_application_language_string_slug'))

    op.drop_table('application_language')
    with op.batch_alter_table('access_protocol', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_access_protocol_string_slug'))

    op.drop_table('access_protocol')
    # ### end Alembic commands ###
