"""Add web push notification, domain for credential

Revision ID: 60f2c3aa1b10
Revises: 461b632c17d7
Create Date: 2026-04-19 10:19:49.654192

"""
from alembic import op
import sqlalchemy as sa
import app


# revision identifiers, used by Alembic.
revision = '60f2c3aa1b10'
down_revision = '461b632c17d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_message_project_id'), ['project_id'], unique=False)

    with op.batch_alter_table('credential', schema=None) as batch_op:
        batch_op.add_column(sa.Column('domain', sa.String(length=50), nullable=True))
        batch_op.create_index(batch_op.f('ix_credential_project_id'), ['project_id'], unique=False)

    with op.batch_alter_table('file_directory', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_file_directory_project_id'), ['project_id'], unique=False)

    with op.batch_alter_table('issue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_number', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_issue_order_number'), ['order_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_issue_project_id'), ['project_id'], unique=False)

    with op.batch_alter_table('network', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_network_project_id'), ['project_id'], unique=False)

    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_note_project_id'), ['project_id'], unique=False)

    with op.batch_alter_table('pentest_organization_detection_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pentest_organization_detection_event_project_id'), ['project_id'], unique=False)

    with op.batch_alter_table('pentest_research_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pentest_research_event_project_id'), ['project_id'], unique=False)

    with op.batch_alter_table('project_additional_field_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_additional_field_data_project_id'), ['project_id'], unique=False)

    with op.batch_alter_table('project_task', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_task_project_id'), ['project_id'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_used_language_code', sa.String(length=7), nullable=True))
        batch_op.add_column(sa.Column('webpush_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('subscription_info', app.models.datatypes.ImmutableJSONType(), nullable=True))

    with op.batch_alter_table('user_notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('require_webpush', sa.Boolean(), server_default=sa.true(), nullable=False))

    with op.batch_alter_table('user_role_has_project', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_role_has_project_project_id'), ['project_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_role_has_project', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_role_has_project_project_id'))

    with op.batch_alter_table('user_notification', schema=None) as batch_op:
        batch_op.drop_column('require_webpush')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('subscription_info')
        batch_op.drop_column('webpush_enabled')
        batch_op.drop_column('last_used_language_code')

    with op.batch_alter_table('project_task', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_task_project_id'))

    with op.batch_alter_table('project_additional_field_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_additional_field_data_project_id'))

    with op.batch_alter_table('pentest_research_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pentest_research_event_project_id'))

    with op.batch_alter_table('pentest_organization_detection_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pentest_organization_detection_event_project_id'))

    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_note_project_id'))

    with op.batch_alter_table('network', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_network_project_id'))

    with op.batch_alter_table('issue', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_issue_project_id'))
        batch_op.drop_index(batch_op.f('ix_issue_order_number'))
        batch_op.drop_column('order_number')

    with op.batch_alter_table('file_directory', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_file_directory_project_id'))

    with op.batch_alter_table('credential', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_credential_project_id'))
        batch_op.drop_column('domain')

    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_message_project_id'))

    # ### end Alembic commands ###
