"""Add vector to issue, some index to objects

Revision ID: 65c3bddd4d2a
Revises: 60f2c3aa1b10
Create Date: 2026-04-24 09:42:54.583896

"""
from alembic import op
import sqlalchemy as sa
import app


# revision identifiers, used by Alembic.
revision = '65c3bddd4d2a'
down_revision = '60f2c3aa1b10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issue_vector',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('string_slug', app.models.datatypes.LimitedLengthString(length=80), nullable=False),
    sa.Column('title', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_issue_vector'))
    )
    with op.batch_alter_table('issue_vector', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_issue_vector_string_slug'), ['string_slug'], unique=True)

    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_message_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comment_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('credential', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_credential_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('credential_import_template', schema=None) as batch_op:
        batch_op.add_column(sa.Column('domain_column_number', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('static_domain', sa.String(length=50), nullable=True))

    with op.batch_alter_table('critical_vulnerability', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_critical_vulnerability_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_critical_vulnerability_proof_of_concept_language_id'), ['proof_of_concept_language_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_critical_vulnerability_vulnerable_environment_type_id'), ['vulnerable_environment_type_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_critical_vulnerability_wikipage_id'), ['wikipage_id'], unique=False)

    with op.batch_alter_table('default_port_and_transport_proto', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_default_port_and_transport_proto_access_protocol_id'), ['access_protocol_id'], unique=False)

    with op.batch_alter_table('file_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_file_data_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('file_directory', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_file_directory_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_file_directory_parent_dir_id'), ['parent_dir_id'], unique=False)

    with op.batch_alter_table('hook', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hook_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('host', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_host_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_host_device_model_id'), ['device_model_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_host_device_type_id'), ['device_type_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_host_device_vendor_id'), ['device_vendor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_host_from_network_id'), ['from_network_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_host_mac_info_id'), ['mac_info_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_host_operation_system_family_id'), ['operation_system_family_id'], unique=False)

    with op.batch_alter_table('issue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vector_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_issue_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_issue_status_id'), ['status_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_issue_vector_id'), ['vector_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_issue_vector_id_issue_vector'), 'issue_vector', ['vector_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('mitre_attack_technique', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mitre_attack_technique_tactic_id'), ['tactic_id'], unique=False)

    with op.batch_alter_table('network', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_network_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_note_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_note_importance_id'), ['importance_id'], unique=False)

    with op.batch_alter_table('pentest_organization_detection_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pentest_organization_detection_event_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_pentest_organization_detection_event_mitre_attack_technique_id'), ['mitre_attack_technique_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pentest_organization_detection_event_source_host_id'), ['source_host_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pentest_organization_detection_event_target_host_id'), ['target_host_id'], unique=False)

    with op.batch_alter_table('pentest_research_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pentest_research_event_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_pentest_research_event_detected_id'), ['detected_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pentest_research_event_mitre_attack_technique_id'), ['mitre_attack_technique_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pentest_research_event_operator_id'), ['operator_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pentest_research_event_prevented_id'), ['prevented_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pentest_research_event_source_host_id'), ['source_host_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pentest_research_event_target_host_id'), ['target_host_id'], unique=False)

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('project_additional_field', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_additional_field_group_id'), ['group_id'], unique=False)

    with op.batch_alter_table('project_additional_field_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_additional_field_data_field_type_id'), ['field_type_id'], unique=False)

    with op.batch_alter_table('project_report_template', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_report_template_template_id'), ['template_id'], unique=False)

    with op.batch_alter_table('project_task', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_task_assigned_to_id'), ['assigned_to_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_task_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_task_priority_id'), ['priority_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_task_state_id'), ['state_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_task_tracker_id'), ['tracker_id'], unique=False)

    with op.batch_alter_table('project_task_template', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_task_template_task_priority_id'), ['task_priority_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_task_template_task_tracker_id'), ['task_tracker_id'], unique=False)

    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_access_protocol_id'), ['access_protocol_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_host_id'), ['host_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_port_state_id'), ['port_state_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_transport_level_protocol_id'), ['transport_level_protocol_id'], unique=False)

    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_leader_id'), ['leader_id'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_avatar_id'), ['avatar_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_position_id'), ['position_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_preferred_language_id'), ['preferred_language_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_theme_style_id'), ['theme_style_id'], unique=False)

    authentication_method_enum = sa.Enum('INFO', 'SUCCESS', 'WARN', "ERROR", name='usernotificationtype')
    authentication_method_enum.create(op.get_bind())
    with op.batch_alter_table('user_notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notification_type', sa.Enum('INFO', 'SUCCESS', 'WARN', 'ERROR', name='usernotificationtype'), server_default='INFO', nullable=False))
        batch_op.create_index(batch_op.f('ix_user_notification_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('user_position_has_object_action', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_position_has_object_action_position_id'), ['position_id'], unique=False)

    with op.batch_alter_table('wiki_directory', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wiki_directory_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('wiki_page', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wiki_page_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wiki_page', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wiki_page_created_at'))

    with op.batch_alter_table('wiki_directory', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wiki_directory_created_at'))

    with op.batch_alter_table('user_position_has_object_action', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_position_has_object_action_position_id'))

    with op.batch_alter_table('user_notification', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_notification_created_at'))
        batch_op.drop_column('notification_type')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_theme_style_id'))
        batch_op.drop_index(batch_op.f('ix_user_preferred_language_id'))
        batch_op.drop_index(batch_op.f('ix_user_position_id'))
        batch_op.drop_index(batch_op.f('ix_user_created_at'))
        batch_op.drop_index(batch_op.f('ix_user_avatar_id'))

    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_leader_id'))

    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_transport_level_protocol_id'))
        batch_op.drop_index(batch_op.f('ix_service_port_state_id'))
        batch_op.drop_index(batch_op.f('ix_service_host_id'))
        batch_op.drop_index(batch_op.f('ix_service_created_at'))
        batch_op.drop_index(batch_op.f('ix_service_access_protocol_id'))

    with op.batch_alter_table('project_task_template', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_task_template_task_tracker_id'))
        batch_op.drop_index(batch_op.f('ix_project_task_template_task_priority_id'))

    with op.batch_alter_table('project_task', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_task_tracker_id'))
        batch_op.drop_index(batch_op.f('ix_project_task_state_id'))
        batch_op.drop_index(batch_op.f('ix_project_task_priority_id'))
        batch_op.drop_index(batch_op.f('ix_project_task_created_at'))
        batch_op.drop_index(batch_op.f('ix_project_task_assigned_to_id'))

    with op.batch_alter_table('project_report_template', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_report_template_template_id'))

    with op.batch_alter_table('project_additional_field_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_additional_field_data_field_type_id'))

    with op.batch_alter_table('project_additional_field', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_additional_field_group_id'))

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_created_at'))

    with op.batch_alter_table('pentest_research_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pentest_research_event_target_host_id'))
        batch_op.drop_index(batch_op.f('ix_pentest_research_event_source_host_id'))
        batch_op.drop_index(batch_op.f('ix_pentest_research_event_prevented_id'))
        batch_op.drop_index(batch_op.f('ix_pentest_research_event_operator_id'))
        batch_op.drop_index(batch_op.f('ix_pentest_research_event_mitre_attack_technique_id'))
        batch_op.drop_index(batch_op.f('ix_pentest_research_event_detected_id'))
        batch_op.drop_index(batch_op.f('ix_pentest_research_event_created_at'))

    with op.batch_alter_table('pentest_organization_detection_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pentest_organization_detection_event_target_host_id'))
        batch_op.drop_index(batch_op.f('ix_pentest_organization_detection_event_source_host_id'))
        batch_op.drop_index(batch_op.f('ix_pentest_organization_detection_event_mitre_attack_technique_id'))
        batch_op.drop_index(batch_op.f('ix_pentest_organization_detection_event_created_at'))

    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_note_importance_id'))
        batch_op.drop_index(batch_op.f('ix_note_created_at'))

    with op.batch_alter_table('network', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_network_created_at'))

    with op.batch_alter_table('mitre_attack_technique', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mitre_attack_technique_tactic_id'))

    with op.batch_alter_table('issue', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_issue_vector_id_issue_vector'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_issue_vector_id'))
        batch_op.drop_index(batch_op.f('ix_issue_status_id'))
        batch_op.drop_index(batch_op.f('ix_issue_created_at'))
        batch_op.drop_column('vector_id')

    with op.batch_alter_table('host', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_host_operation_system_family_id'))
        batch_op.drop_index(batch_op.f('ix_host_mac_info_id'))
        batch_op.drop_index(batch_op.f('ix_host_from_network_id'))
        batch_op.drop_index(batch_op.f('ix_host_device_vendor_id'))
        batch_op.drop_index(batch_op.f('ix_host_device_type_id'))
        batch_op.drop_index(batch_op.f('ix_host_device_model_id'))
        batch_op.drop_index(batch_op.f('ix_host_created_at'))

    with op.batch_alter_table('hook', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hook_created_at'))

    with op.batch_alter_table('file_directory', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_file_directory_parent_dir_id'))
        batch_op.drop_index(batch_op.f('ix_file_directory_created_at'))

    with op.batch_alter_table('file_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_file_data_created_at'))

    with op.batch_alter_table('default_port_and_transport_proto', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_default_port_and_transport_proto_access_protocol_id'))

    with op.batch_alter_table('critical_vulnerability', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_critical_vulnerability_wikipage_id'))
        batch_op.drop_index(batch_op.f('ix_critical_vulnerability_vulnerable_environment_type_id'))
        batch_op.drop_index(batch_op.f('ix_critical_vulnerability_proof_of_concept_language_id'))
        batch_op.drop_index(batch_op.f('ix_critical_vulnerability_created_at'))

    with op.batch_alter_table('credential_import_template', schema=None) as batch_op:
        batch_op.drop_column('static_domain')
        batch_op.drop_column('domain_column_number')

    with op.batch_alter_table('credential', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_credential_created_at'))

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comment_created_at'))

    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_message_created_at'))

    with op.batch_alter_table('issue_vector', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_issue_vector_string_slug'))

    op.drop_table('issue_vector')
    # ### end Alembic commands ###
