"""Добавлено поле comment для заводских учётных данных

Revision ID: 671c329b7d0c
Revises: 6a6686b97c85
Create Date: 2025-03-28 16:48:37.523043

"""
from alembic import op
import sqlalchemy as sa
import app


# revision identifiers, used by Alembic.
revision = '671c329b7d0c'
down_revision = '6a6686b97c85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('default_credential', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment', sa.String(length=150), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('default_credential', schema=None) as batch_op:
        batch_op.drop_column('comment')

    # ### end Alembic commands ###
