"""Добавлены заводские учётные данные

Revision ID: 6a6686b97c85
Revises: dfed10df89d1
Create Date: 2025-03-27 23:06:41.309498

"""
from alembic import op
import sqlalchemy as sa
import app


# revision identifiers, used by Alembic.
revision = '6a6686b97c85'
down_revision = 'dfed10df89d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('default_credential',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('string_slug', app.models.datatypes.LimitedLengthString(length=80), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.Column('login', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_default_credential'))
    )
    with op.batch_alter_table('default_credential', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_default_credential_string_slug'), ['string_slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_default_credential_title'), ['title'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('default_credential', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_default_credential_title'))
        batch_op.drop_index(batch_op.f('ix_default_credential_string_slug'))

    op.drop_table('default_credential')
    # ### end Alembic commands ###
