"""Добавлены события исследования

Revision ID: 893d13d91921
Revises: cc93c68ecf71
Create Date: 2025-03-03 13:16:04.323239

"""
from alembic import op
import sqlalchemy as sa
import app


# revision identifiers, used by Alembic.
revision = '893d13d91921'
down_revision = 'cc93c68ecf71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evidence_of_event_detected',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('string_slug', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence_of_event_detected'))
    )
    with op.batch_alter_table('evidence_of_event_detected', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_of_event_detected_string_slug'), ['string_slug'], unique=True)

    op.create_table('evidence_of_event_prevented',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('string_slug', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence_of_event_prevented'))
    )
    with op.batch_alter_table('evidence_of_event_prevented', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_of_event_prevented_string_slug'), ['string_slug'], unique=True)

    op.create_table('mitre_attack_tactic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('string_slug', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mitre_attack_tactic'))
    )
    with op.batch_alter_table('mitre_attack_tactic', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mitre_attack_tactic_string_slug'), ['string_slug'], unique=True)

    op.create_table('mitre_attack_technique',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('string_slug', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('tactic_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tactic_id'], ['mitre_attack_tactic.id'], name=op.f('fk_mitre_attack_technique_tactic_id_mitre_attack_tactic'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mitre_attack_technique'))
    )
    with op.batch_alter_table('mitre_attack_technique', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mitre_attack_technique_string_slug'), ['string_slug'], unique=True)

    op.create_table('pentest_organization_detection_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('source_host_id', sa.Integer(), nullable=True),
    sa.Column('source_user', sa.String(length=50), nullable=True),
    sa.Column('source_process', sa.String(length=80), nullable=True),
    sa.Column('target_host_id', sa.Integer(), nullable=True),
    sa.Column('target_user', sa.String(length=50), nullable=True),
    sa.Column('target_process', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('mitre_attack_technique_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], name=op.f('fk_pentest_organization_detection_event_created_by_id_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['mitre_attack_technique_id'], ['mitre_attack_technique.id'], name=op.f('fk_pentest_organization_detection_event_mitre_attack_technique_id_mitre_attack_technique'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('fk_pentest_organization_detection_event_project_id_project'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_host_id'], ['host.id'], name=op.f('fk_pentest_organization_detection_event_source_host_id_host'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_host_id'], ['host.id'], name=op.f('fk_pentest_organization_detection_event_target_host_id_host'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['user.id'], name=op.f('fk_pentest_organization_detection_event_updated_by_id_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pentest_organization_detection_event'))
    )
    op.create_table('pentest_research_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('source_host_id', sa.Integer(), nullable=True),
    sa.Column('source_user', sa.String(length=50), nullable=True),
    sa.Column('source_process', sa.String(length=80), nullable=True),
    sa.Column('target_host_id', sa.Integer(), nullable=True),
    sa.Column('target_user', sa.String(length=50), nullable=True),
    sa.Column('target_process', sa.String(length=80), nullable=True),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('raw_evidence', sa.String(), nullable=True),
    sa.Column('detected_id', sa.Integer(), nullable=True),
    sa.Column('prevented_id', sa.Integer(), nullable=True),
    sa.Column('mitre_attack_technique_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], name=op.f('fk_pentest_research_event_created_by_id_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['detected_id'], ['evidence_of_event_detected.id'], name=op.f('fk_pentest_research_event_detected_id_evidence_of_event_detected'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['mitre_attack_technique_id'], ['mitre_attack_technique.id'], name=op.f('fk_pentest_research_event_mitre_attack_technique_id_mitre_attack_technique'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['operator_id'], ['user.id'], name=op.f('fk_pentest_research_event_operator_id_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['prevented_id'], ['evidence_of_event_prevented.id'], name=op.f('fk_pentest_research_event_prevented_id_evidence_of_event_prevented'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('fk_pentest_research_event_project_id_project'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_host_id'], ['host.id'], name=op.f('fk_pentest_research_event_source_host_id_host'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_host_id'], ['host.id'], name=op.f('fk_pentest_research_event_target_host_id_host'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['user.id'], name=op.f('fk_pentest_research_event_updated_by_id_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pentest_research_event'))
    )
    op.create_table('pentest_organization_detection_event_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('changes', app.models.datatypes.JSONType(), nullable=True),
    sa.Column('to_object_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], name=op.f('fk_pentest_organization_detection_event_history_created_by_id_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['to_object_id'], ['pentest_organization_detection_event.id'], name=op.f('fk_pentest_organization_detection_event_history_to_object_id_pentest_organization_detection_event'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pentest_organization_detection_event_history'))
    )
    op.create_table('pentest_research_event_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('changes', app.models.datatypes.JSONType(), nullable=True),
    sa.Column('to_object_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], name=op.f('fk_pentest_research_event_history_created_by_id_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['to_object_id'], ['pentest_research_event.id'], name=op.f('fk_pentest_research_event_history_to_object_id_pentest_research_event'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pentest_research_event_history'))
    )
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.alter_column('to_object_type',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=50),
               existing_nullable=False)

    with op.batch_alter_table('role_has_project_object_action', schema=None) as batch_op:
        batch_op.alter_column('object_class_name',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.String(length=40),
               existing_nullable=False)
        batch_op.alter_column('action',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.String(length=40),
               existing_nullable=False)

    with op.batch_alter_table('user_theme_style', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timeline_time_color', sa.String(length=40), server_default='#8796af', nullable=False))
        batch_op.add_column(sa.Column('timeline_line_color', sa.String(length=40), server_default='#000', nullable=False))
        batch_op.add_column(sa.Column('timeline_red_team_background_color', sa.String(length=40), server_default='rgb(138, 2, 2)', nullable=False))
        batch_op.add_column(sa.Column('timeline_red_team_text_color', sa.String(length=40), server_default='#fff', nullable=False))
        batch_op.add_column(sa.Column('timeline_blue_team_background_color', sa.String(length=40), server_default='rgb(0, 0, 138)', nullable=False))
        batch_op.add_column(sa.Column('timeline_blue_team_text_color', sa.String(length=40), server_default='#fff', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_theme_style', schema=None) as batch_op:
        batch_op.drop_column('timeline_blue_team_text_color')
        batch_op.drop_column('timeline_blue_team_background_color')
        batch_op.drop_column('timeline_red_team_text_color')
        batch_op.drop_column('timeline_red_team_background_color')
        batch_op.drop_column('timeline_line_color')
        batch_op.drop_column('timeline_time_color')

    with op.batch_alter_table('role_has_project_object_action', schema=None) as batch_op:
        batch_op.alter_column('action',
               existing_type=sa.String(length=40),
               type_=sa.VARCHAR(length=15),
               existing_nullable=False)
        batch_op.alter_column('object_class_name',
               existing_type=sa.String(length=40),
               type_=sa.VARCHAR(length=15),
               existing_nullable=False)

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.alter_column('to_object_type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)

    op.drop_table('pentest_research_event_history')
    op.drop_table('pentest_organization_detection_event_history')
    op.drop_table('pentest_research_event')
    op.drop_table('pentest_organization_detection_event')
    with op.batch_alter_table('mitre_attack_technique', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mitre_attack_technique_string_slug'))

    op.drop_table('mitre_attack_technique')
    with op.batch_alter_table('mitre_attack_tactic', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mitre_attack_tactic_string_slug'))

    op.drop_table('mitre_attack_tactic')
    with op.batch_alter_table('evidence_of_event_prevented', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_of_event_prevented_string_slug'))

    op.drop_table('evidence_of_event_prevented')
    with op.batch_alter_table('evidence_of_event_detected', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_of_event_detected_string_slug'))

    op.drop_table('evidence_of_event_detected')
    # ### end Alembic commands ###
