"""Added hooks for objects

Revision ID: 8b05c995a642
Revises: b9fa2bbcd8b0
Create Date: 2026-01-31 17:46:30.859260

"""
from alembic import op
import sqlalchemy as sa
import app


# revision identifiers, used by Alembic.
revision = '8b05c995a642'
down_revision = 'b9fa2bbcd8b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hook',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('on_object', sa.Enum('USER', 'ISSUE', 'PROJECT', 'PROJECTTASK', 'CHATMESSAGE', 'CREDENTIAL', 'NETWORK', 'HOST', 'SERVICE', 'NOTE', 'WIKIPAGE', 'PENTESTRESEARCHEVENT', 'PENTESTORGANIZATIONDETECTIONEVENT', name='objectwithhook'), nullable=False),
    sa.Column('on_action', sa.Enum('CREATE', 'UPDATE', 'DESTROY', 'ADD_COMMENT', name='objectwithhookaction'), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hook'))
    )
    with op.batch_alter_table('project_task_template', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_default', sa.Boolean(), server_default=sa.text('0'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_task_template', schema=None) as batch_op:
        batch_op.drop_column('is_default')

    op.drop_table('hook')
    # ### end Alembic commands ###
