"""Стили графа сети, VLAN ID, изменения User Position

Revision ID: a8e7a2ec87f6
Revises: f47e0bd8f56a
Create Date: 2025-07-26 11:51:42.911343

"""
from alembic import op
import sqlalchemy as sa
import app


# revision identifiers, used by Alembic.
revision = 'a8e7a2ec87f6'
down_revision = 'f47e0bd8f56a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('default_port_and_transport_proto', schema=None) as batch_op:
        batch_op.alter_column('transport_level_protocol_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('access_protocol_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('network', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vlan_number', sa.Integer(), nullable=True))

    with op.batch_alter_table('user_position', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_administrator', sa.Boolean(), server_default=sa.false(), nullable=False))

    with op.batch_alter_table('user_theme_style', schema=None) as batch_op:
        batch_op.add_column(sa.Column('network_on_graph_color', sa.String(length=40), server_default='green', nullable=False))
        batch_op.add_column(sa.Column('normal_host_color', sa.String(length=40), server_default='#0000ff', nullable=False))
        batch_op.add_column(sa.Column('service_on_graph_color', sa.String(length=40), server_default='yellow', nullable=False))
    
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("is_administrator")
    
    with op.batch_alter_table('user_has_team', schema=None) as batch_op:
        batch_op.drop_constraint("pk_user_has_team", type_='primary')
        batch_op.create_primary_key("pk_user_has_team", ["user_id", "team_id", "role_id"])
    
    op.create_table('user_position_has_object_action',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('object_class_name', sa.String(length=40), nullable=False),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('is_granted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['position_id'], ['user_position.id'], name=op.f('fk_user_position_has_object_action_position_id_user_position'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_position_has_object_action'))
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_theme_style', schema=None) as batch_op:
        batch_op.drop_column('service_on_graph_color')
        batch_op.drop_column('normal_host_color')
        batch_op.drop_column('network_on_graph_color')

    with op.batch_alter_table('user_position', schema=None) as batch_op:
        batch_op.drop_column('is_administrator')
    
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(sa.Column("is_administrator", sa.BOOLEAN(), server_default=sa.false(), nullable=False))

    with op.batch_alter_table('network', schema=None) as batch_op:
        batch_op.drop_column('vlan_number')

    with op.batch_alter_table('default_port_and_transport_proto', schema=None) as batch_op:
        batch_op.alter_column('access_protocol_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('transport_level_protocol_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    
    with op.batch_alter_table('user_has_team', schema=None) as batch_op:
        batch_op.drop_constraint('pk_user_has_team', type_='primary')
        batch_op.create_primary_key("pk_user_has_team", ["user_id", "team_id"])
    
    op.drop_table('user_position_has_object_action')

    # ### end Alembic commands ###
