"""add new fields for vectors and issues

Revision ID: a911c2c4c265
Revises: 65c3bddd4d2a
Create Date: 2026-04-24 21:59:24.946268

"""
from alembic import op
import sqlalchemy as sa
import app


# revision identifiers, used by Alembic.
revision = 'a911c2c4c265'
down_revision = '65c3bddd4d2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issue_status', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_default', sa.Boolean(), nullable=False, server_default=sa.false()))

    with op.batch_alter_table('issue_template', schema=None) as batch_op:
        batch_op.add_column(sa.Column('issue_vector_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_issue_template_issue_vector_id_issue_vector'), 'issue_vector', ['issue_vector_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('issue_vector', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_default', sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issue_vector', schema=None) as batch_op:
        batch_op.drop_column('is_default')

    with op.batch_alter_table('issue_template', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_issue_template_issue_vector_id_issue_vector'), type_='foreignkey')
        batch_op.drop_column('issue_vector_id')

    with op.batch_alter_table('issue_status', schema=None) as batch_op:
        batch_op.drop_column('is_default')

    # ### end Alembic commands ###
