"""Обновлены наименования атрибутов хоста

Revision ID: b9fa2bbcd8b0
Revises: 1115b88acd5c
Create Date: 2025-09-03 17:46:24.185895

"""
from alembic import op
import sqlalchemy as sa
import app


# revision identifiers, used by Alembic.
revision = 'b9fa2bbcd8b0'
down_revision = '1115b88acd5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('host', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('status_reason', sa.String(length=50), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_host_state_id_host_status'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_host_status_id_host_status'), 'host_status', ['status_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_column('state_reason')
        batch_op.drop_column('state_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('host', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('state_reason', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_host_status_id_host_status'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_host_state_id_host_status'), 'host_status', ['state_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_column('status_reason')
        batch_op.drop_column('status_id')

    # ### end Alembic commands ###
