"""empty message

Revision ID: bb61d0326835
Revises: efd893acb818
Create Date: 2025-02-18 22:15:28.960115

"""
from alembic import op
import sqlalchemy as sa
import app


# revision identifiers, used by Alembic.
revision = 'bb61d0326835'
down_revision = 'efd893acb818'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credential_import_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('string_slug', app.models.datatypes.LimitedLengthString(length=80), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('login_column_number', sa.Integer(), nullable=True),
    sa.Column('password_hash_column_number', sa.Integer(), nullable=True),
    sa.Column('description_column_number', sa.Integer(), nullable=True),
    sa.Column('password_column_number', sa.Integer(), nullable=True),
    sa.Column('static_login', sa.String(length=40), nullable=True),
    sa.Column('static_password_hash', sa.String(), nullable=True),
    sa.Column('static_hash_type_id', sa.Integer(), nullable=True),
    sa.Column('static_check_wordlist_id', sa.Integer(), nullable=True),
    sa.Column('static_description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['static_check_wordlist_id'], ['check_wordlist.id'], name=op.f('fk_credential_import_template_static_check_wordlist_id_check_wordlist'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['static_hash_type_id'], ['hash_type.id'], name=op.f('fk_credential_import_template_static_hash_type_id_hash_type'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_credential_import_template'))
    )
    with op.batch_alter_table('credential_import_template', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_credential_import_template_string_slug'), ['string_slug'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credential_import_template', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_credential_import_template_string_slug'))

    op.drop_table('credential_import_template')
    # ### end Alembic commands ###
