"""Added domains

Revision ID: bbf9014ef105
Revises: a911c2c4c265
Create Date: 2026-05-22 19:21:21.206040

"""
from alembic import op
import sqlalchemy as sa
import app


# revision identifiers, used by Alembic.
revision = 'bbf9014ef105'
down_revision = 'a911c2c4c265'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domain',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], name=op.f('fk_domain_created_by_id_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('fk_domain_project_id_project'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['user.id'], name=op.f('fk_domain_updated_by_id_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_domain'))
    )
    with op.batch_alter_table('domain', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_domain_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_domain_project_id'), ['project_id'], unique=False)

    op.create_table('domain_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('changes', app.models.datatypes.ImmutableJSONType(), nullable=True),
    sa.Column('to_object_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], name=op.f('fk_domain_history_created_by_id_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['to_object_id'], ['domain.id'], name=op.f('fk_domain_history_to_object_id_domain'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_domain_history'))
    )
    with op.batch_alter_table('credential', schema=None) as batch_op:
        batch_op.add_column(sa.Column('domain_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_credential_domain_id'), ['domain_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_credential_domain_id_domain'), 'domain', ['domain_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_column('domain')

    with op.batch_alter_table('credential_import_template', schema=None) as batch_op:
        batch_op.drop_column('static_domain')

    with op.batch_alter_table('host', schema=None) as batch_op:
        batch_op.add_column(sa.Column('domain_controller_for_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('domain_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_host_domain_controller_for_id_domain'), 'domain', ['domain_controller_for_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('fk_host_domain_id_domain'), 'domain', ['domain_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('host', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_host_domain_id_domain'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_host_domain_controller_for_id_domain'), type_='foreignkey')
        batch_op.drop_column('domain_id')
        batch_op.drop_column('domain_controller_for_id')

    with op.batch_alter_table('credential_import_template', schema=None) as batch_op:
        batch_op.add_column(sa.Column('static_domain', sa.VARCHAR(length=50), nullable=True))

    with op.batch_alter_table('credential', schema=None) as batch_op:
        batch_op.add_column(sa.Column('domain', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_credential_domain_id_domain'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_credential_domain_id'))
        batch_op.drop_column('domain_id')

    op.drop_table('domain_history')
    with op.batch_alter_table('domain', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_domain_project_id'))
        batch_op.drop_index(batch_op.f('ix_domain_created_at'))

    op.drop_table('domain')
    # ### end Alembic commands ###
