"""Изменения для инвентаризатора, доработки интерфейса

Revision ID: cc93c68ecf71
Revises: bb61d0326835
Create Date: 2025-02-26 21:30:43.990594

"""
from alembic import op
import sqlalchemy as sa
import app


# revision identifiers, used by Alembic.
revision = 'cc93c68ecf71'
down_revision = 'bb61d0326835'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.add_column(sa.Column('http_title', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('https_title', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('has_been_inventoried', sa.Boolean(), server_default=sa.text('0'), nullable=False))

    with op.batch_alter_table('user_theme_style', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dark_color', sa.String(length=40), server_default="#777", nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_theme_style', schema=None) as batch_op:
        batch_op.drop_column('dark_color')

    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.drop_column('has_been_inventoried')
        batch_op.drop_column('https_title')
        batch_op.drop_column('http_title')

    # ### end Alembic commands ###
