"""Добавлена парольная политика и дополнительные параметры

Revision ID: dfed10df89d1
Revises: 893d13d91921
Create Date: 2025-03-21 07:50:46.994810

"""
from alembic import op
import sqlalchemy as sa
import app


# revision identifiers, used by Alembic.
revision = 'dfed10df89d1'
down_revision = '893d13d91921'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_additional_field_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('string_slug', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('order_number', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_additional_field_group'))
    )
    with op.batch_alter_table('project_additional_field_group', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_additional_field_group_string_slug'), ['string_slug'], unique=True)

    op.create_table('project_additional_field',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('string_slug', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('help_text', sa.String(length=150), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('field_type', sa.String(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['project_additional_field_group.id'], name=op.f('fk_project_additional_field_group_id_project_additional_field_group'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_additional_field'))
    )
    with op.batch_alter_table('project_additional_field', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_additional_field_string_slug'), ['string_slug'], unique=True)

    op.create_table('project_additional_field_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('field_type_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['field_type_id'], ['project_additional_field.id'], name=op.f('fk_project_additional_field_data_field_type_id_project_additional_field'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('fk_project_additional_field_data_project_id_project'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['user.id'], name=op.f('fk_project_additional_field_data_updated_by_id_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_additional_field_data')),
    sa.UniqueConstraint('field_type_id', 'project_id', name='_unique_field_type_id_and_project_id_together')
    )
    with op.batch_alter_table('global_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('m2m_join_symbol', sa.String(length=10), server_default=';<br>', nullable=False))
        batch_op.add_column(sa.Column('m2m_max_items', sa.Integer(), server_default='4', nullable=False))
        batch_op.add_column(sa.Column('pagination_element_count_select2', sa.Integer(), server_default='30', nullable=False))
        batch_op.add_column(sa.Column('password_min_length', sa.Integer(), server_default='1', nullable=False))
        batch_op.add_column(sa.Column('password_lifetime', sa.Integer(), server_default='3650', nullable=False))
        batch_op.add_column(sa.Column('password_lowercase_symbol_require', sa.Boolean(), server_default=sa.false(), nullable=False))
        batch_op.add_column(sa.Column('password_uppercase_symbol_require', sa.Boolean(), server_default=sa.false(), nullable=False))
        batch_op.add_column(sa.Column('password_numbers_require', sa.Boolean(), server_default=sa.false(), nullable=False))
        batch_op.add_column(sa.Column('password_special_symbols_require', sa.Boolean(), server_default=sa.false(), nullable=False))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_password_expired', sa.Boolean(), server_default=sa.true(), nullable=False))
        batch_op.add_column(sa.Column('password_expired_date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('password_expired_date')
        batch_op.drop_column('is_password_expired')

    with op.batch_alter_table('global_settings', schema=None) as batch_op:
        batch_op.drop_column('password_special_symbols_require')
        batch_op.drop_column('password_numbers_require')
        batch_op.drop_column('password_uppercase_symbol_require')
        batch_op.drop_column('password_lowercase_symbol_require')
        batch_op.drop_column('password_lifetime')
        batch_op.drop_column('password_min_length')
        batch_op.drop_column('pagination_element_count_select2')
        batch_op.drop_column('m2m_max_items')
        batch_op.drop_column('m2m_join_symbol')

    op.drop_table('project_additional_field_data')
    with op.batch_alter_table('project_additional_field', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_additional_field_string_slug'))

    op.drop_table('project_additional_field')
    with op.batch_alter_table('project_additional_field_group', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_additional_field_group_string_slug'))

    op.drop_table('project_additional_field_group')
    # ### end Alembic commands ###
