"""Added credential sources, change issue

Revision ID: efd893acb818
Revises: 464958bad06e
Create Date: 2025-02-14 18:12:50.887340

"""
from alembic import op
import sqlalchemy as sa
import app


# revision identifiers, used by Alembic.
revision = 'efd893acb818'
down_revision = '464958bad06e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credential_by_received_host',
    sa.Column('credential_id', sa.Integer(), nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['credential_id'], ['credential.id'], name=op.f('fk_credential_by_received_host_credential_id_credential'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['host_id'], ['host.id'], name=op.f('fk_credential_by_received_host_host_id_host'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('credential_id', 'host_id', name=op.f('pk_credential_by_received_host'))
    )
    with op.batch_alter_table('credential', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=70),
               nullable=True)

    with op.batch_alter_table('credential_by_service', schema=None) as batch_op:
        batch_op.drop_constraint('fk_credential_by_service_credential_id_credential', type_='foreignkey')
        batch_op.drop_constraint('fk_credential_by_service_service_id_service', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_credential_by_service_service_id_service'), 'service', ['service_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_credential_by_service_credential_id_credential'), 'credential', ['credential_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('issue', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)

    with op.batch_alter_table('issue_template', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('issue_title',
               existing_type=sa.VARCHAR(length=50),
               type_=app.models.datatypes.LimitedLengthString(length=100),
               existing_nullable=False)

    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.alter_column('port_state_reason',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.alter_column('port_state_reason',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('issue_template', schema=None) as batch_op:
        batch_op.alter_column('issue_title',
               existing_type=app.models.datatypes.LimitedLengthString(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('issue', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('credential_by_service', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_credential_by_service_credential_id_credential'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_credential_by_service_service_id_service'), type_='foreignkey')
        batch_op.create_foreign_key('fk_credential_by_service_service_id_service', 'service', ['service_id'], ['id'])
        batch_op.create_foreign_key('fk_credential_by_service_credential_id_credential', 'credential', ['credential_id'], ['id'])

    with op.batch_alter_table('credential', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=70),
               nullable=False)
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(),
               nullable=False)

    op.drop_table('credential_by_received_host')
    # ### end Alembic commands ###
