"""empty message

Revision ID: f19d0ae7f1e4
Revises: 4c8c3586aa6e
Create Date: 2025-02-11 23:12:04.286782

"""
from alembic import op
import sqlalchemy as sa
import app


# revision identifiers, used by Alembic.
revision = 'f19d0ae7f1e4'
down_revision = '4c8c3586aa6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('host_another_interface',
    sa.Column('first_interface_id', sa.Integer(), nullable=False),
    sa.Column('second_interface_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['first_interface_id'], ['host.id'], name=op.f('fk_host_another_interface_first_interface_id_host'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['second_interface_id'], ['host.id'], name=op.f('fk_host_another_interface_second_interface_id_host'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('first_interface_id', 'second_interface_id', name=op.f('pk_host_another_interface'))
    )
    with op.batch_alter_table('state_to_state_task', schema=None) as batch_op:
        batch_op.drop_constraint('fk_state_to_state_task_to_state_id_task_state', type_='foreignkey')
        batch_op.drop_constraint('fk_state_to_state_task_from_state_id_task_state', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_state_to_state_task_to_state_id_task_state'), 'task_state', ['to_state_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_state_to_state_task_from_state_id_task_state'), 'task_state', ['from_state_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('state_to_state_task', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_state_to_state_task_from_state_id_task_state'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_state_to_state_task_to_state_id_task_state'), type_='foreignkey')
        batch_op.create_foreign_key('fk_state_to_state_task_from_state_id_task_state', 'task_state', ['from_state_id'], ['id'])
        batch_op.create_foreign_key('fk_state_to_state_task_to_state_id_task_state', 'task_state', ['to_state_id'], ['id'])

    op.drop_table('host_another_interface')
    # ### end Alembic commands ###
