"""Добавлены nmap-отпечатки и метки скомпрометированных хостов

Revision ID: f47e0bd8f56a
Revises: 3b99fb344302
Create Date: 2025-07-08 10:05:19.132576

"""
from alembic import op
import sqlalchemy as sa
import app


# revision identifiers, used by Alembic.
revision = 'f47e0bd8f56a'
down_revision = '3b99fb344302'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mutual_network_visibility',
    sa.Column('from_network_id', sa.Integer(), nullable=False),
    sa.Column('to_network_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['from_network_id'], ['network.id'], name=op.f('fk_mutual_network_visibility_from_network_id_network'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_network_id'], ['network.id'], name=op.f('fk_mutual_network_visibility_to_network_id_network'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('from_network_id', 'to_network_id', name=op.f('pk_mutual_network_visibility'))
    )
    op.create_table('accessible_service_has_host',
    sa.Column('accessible_service_id', sa.Integer(), nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['accessible_service_id'], ['service.id'], name=op.f('fk_accessible_service_has_host_accessible_service_id_service'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['host_id'], ['host.id'], name=op.f('fk_accessible_service_has_host_host_id_host'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('accessible_service_id', 'host_id', name=op.f('pk_accessible_service_has_host'))
    )
    op.create_table('pentest_event_chain',
    sa.Column('from_event_id', sa.Integer(), nullable=False),
    sa.Column('to_event_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['from_event_id'], ['pentest_research_event.id'], name=op.f('fk_pentest_event_chain_from_event_id_pentest_research_event'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_event_id'], ['pentest_research_event.id'], name=op.f('fk_pentest_event_chain_to_event_id_pentest_research_event'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('from_event_id', 'to_event_id', name=op.f('pk_pentest_event_chain'))
    )
    with op.batch_alter_table('host', schema=None) as batch_op:
        batch_op.add_column(sa.Column('compromised', sa.Boolean(), server_default=sa.false(), nullable=False))

    with op.batch_alter_table('operation_system_family', schema=None) as batch_op:
        batch_op.add_column(sa.Column('icon', sa.String(length=30), nullable=True))

    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nmap_fingerprint', sa.String(), nullable=True))

    with op.batch_alter_table('user_theme_style', schema=None) as batch_op:
        batch_op.add_column(sa.Column('compromised_host_color', sa.String(length=40), server_default='#ff0000', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_theme_style', schema=None) as batch_op:
        batch_op.drop_column('compromised_host_color')

    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.drop_column('nmap_fingerprint')

    with op.batch_alter_table('operation_system_family', schema=None) as batch_op:
        batch_op.drop_column('icon')

    with op.batch_alter_table('host', schema=None) as batch_op:
        batch_op.drop_column('compromised')

    op.drop_table('pentest_event_chain')
    op.drop_table('accessible_service_has_host')
    op.drop_table('mutual_network_visibility')
    # ### end Alembic commands ###
